items_component = [
    # Tags
    {"item_name": "Federation Navy Fleet Colonel Insignia I", "id": 15594},
    {"item_name": "Federation Navy Fleet Colonel Insignia II", "id": 15673},
    {"item_name": "Federation Navy Command Sergeant Major Insignia I", "id": 15646},
    {"item_name": "Federation Navy Fleet Major Insignia I", "id": 15593},
    {"item_name": "Federation Navy Fleet Captain Insignia I", "id": 15592},

    {"item_name": "Federation Navy Sergeant Insignia I", "id": 15590},
    {"item_name": "Federation Navy Sergeant Insignia II", "id": 15994},
    {"item_name": "Federation Navy Sergeant Insignia III", "id": 16002},

    {"item_name": "Dread Guristas Gold Tag", "id": 17248},

    # Shield Extenders
    {"item_name": "Large Shield Extender I", "id": 3839},
    {"item_name": "Medium Shield Extender I", "id": 3829},
    {"item_name": "Small Shield Extender I", "id": 377},

    {"item_name": "Cap Booster 25", "id": 263},
    {"item_name": "Cap Booster 50", "id": 264},
    {"item_name": "Cap Booster 75", "id": 3552},
    {"item_name": "Cap Booster 100", "id": 3554},
    {"item_name": "Cap Booster 150", "id": 11283},
    {"item_name": "Cap Booster 200", "id": 11285},
    {"item_name": "Cap Booster 400", "id": 11287},
    {"item_name": "Cap Booster 800", "id": 11289},
    {"item_name": "Cap Booster 3200", "id": 41489},

    {"item_name": "Multispectrum Shield Hardener I", "id": 578},
    {"item_name": "EM Shield Hardener I", "id": 2293},
    {"item_name": "Explosive Shield Hardener I", "id": 2289},
    {"item_name": "Kinetic Shield Hardener I", "id": 2291},
    {"item_name": "Thermal Shield Hardener I", "id": 2295},

    # Shield Boosters
    {"item_name": "Small Shield Booster I", "id": 399},
    {"item_name": "Medium Shield Booster I", "id": 10836},
    {"item_name": "Large Shield Booster I", "id": 10838},
    {"item_name": "X-Large Shield Booster I", "id": 10840},

    {"item_name": "Shield Boost Amplifier I", "id": 11561},

    # Modules
    {"item_name": "Micro Auxiliary Power Core I", "id": 11563},
    {"item_name": "Power Diagnostic System I", "id": 1539},
    {"item_name": "Co-Processor I", "id": 3887},
    {"item_name": "Warp Scrambler I", "id": 447},
    {"item_name": "Warp Disruptor I", "id": 3242},
    {"item_name": "Stasis Webifier I", "id": 526},
    {"item_name": "Prototype Cloaking Device I", "id": 11370},

    {"item_name": "Ballistic Control System I", "id": 12274},

    # Drones
    {"item_name": "Hornet I", "id": 2464},
    {"item_name": "Vespa I", "id": 15508},
    {"item_name": "Wasp I", "id": 1201},

    # Launcher
    {"item_name": "Rapid Light Missile Launcher I", "id": 1875},
    {"item_name": "Rapid Heavy Missile Launcher I", "id": 33448},
    {"item_name": "Light Missile Launcher I", "id": 499},
    {"item_name": "Heavy Missile Launcher I", "id": 501},
    {"item_name": "Rocket Launcher I", "id": 10629},
    {"item_name": "Cruise Missile Launcher I", "id": 13320},
    {"item_name": "Torpedo Launcher I", "id": 503},

    # Railguns
    {"item_name": "425mm Railgun I", "id": 574},
    {"item_name": "350mm Railgun I", "id": 12354},
    {"item_name": "Dual 250mm Railgun I", "id": 572},
    {"item_name": "150mm Railgun I", "id": 565},
    {"item_name": "75mm Gatling Rail I", "id": 561},
    {"item_name": "Dual 150mm Railgun I", "id": 567},
    {"item_name": "250mm Railgun I", "id": 570},
    {"item_name": "125mm Railgun I", "id": 10678},
    {"item_name": "200mm Railgun I", "id": 12344},

    # SmartBombs
    {"item_name": "Small Graviton Smartbomb I", "id": 1551},
    {"item_name": "Medium Graviton Smartbomb I", "id": 3941},
    {"item_name": "Large Graviton Smartbomb I", "id": 3981},

    # Resources
    {"item_name": "Megacyte", "id": 40},
    {"item_name": "Zydrine", "id":39},
    {"item_name": "Nocxium", "id":38},
    {"item_name": "Isogen", "id":37},
    {"item_name": "Mexallon", "id":36},
    {"item_name": "Pyerite", "id":35},
    {"item_name": "Tritanium", "id":34},
    {"item_name": "Auto-Integrity Preservation Seal", "id": 57478},
    {"item_name": "Life Support Backup Unit", "id": 57486},
#    {"item_name": "Core Temperature Regulator", "id": 57479},

    # Components
    {"item_name": "Core Temperature Regulator", "id": 57479},
    # Capital Components
#    {"item_name": "Neurolink Protection Cell", "id": 57488},
#    {"item_name": "Capital Sensor Cluster", "id": 21013},
#    {"item_name": "Capital Armor Plates", "id": 21017},
#    {"item_name": "Capital Capacitor Battery", "id": 21019},
#    {"item_name": "Capital Power Generator", "id": 21021},
#    {"item_name": "Capital Jump Drive", "id": 21025},
#    {"item_name": "Capital Construction Parts", "id": 21037},
#    {"item_name": "Capital Corporate Hangar Bay", "id": 24560},
#    {"item_name": "Gravimetric-FTL Interlink Communicator", "id": 57475},
#    {"item_name": "Capital Computer System", "id": 21035},
#    {"item_name": "Capital Propulsion Engine", "id": 21009},
#    {"item_name": "Capital Shield Emitter", "id": 21023},
#    {"item_name": "Capital Ship Maintenance Bay", "id": 24558},
#    {"item_name": "R-O Trigger Neurolink Conduit", "id": 57471},
#    {"item_name": "Capital Siege Array", "id": 21039},
#    {"item_name": "Capital Launcher Hardpoint", "id": 21041},

    # Missile
    {"item_name": "Inferno Light Missile", "id": 211},
    {"item_name": "Mjolnir Light Missile", "id": 212},
    {"item_name": "Nova Light Missile", "id": 213},
    {"item_name": "Scourge Light Missile", "id": 210},

    {"item_name": "Inferno Heavy Missile", "id": 208},
    {"item_name": "Mjolnir Heavy Missile", "id": 207},
    {"item_name": "Nova Heavy Missile", "id": 206},
    {"item_name": "Scourge Heavy Missile", "id": 209},

    {"item_name": "Inferno Heavy Assault Missile", "id": 20308},
    {"item_name": "Mjolnir Heavy Assault Missile", "id": 20306},
    {"item_name": "Nova Heavy Assault Missile", "id": 21867},
    {"item_name": "Scourge Heavy Assault Missile", "id": 20307},

    {"item_name": "Inferno Cruise Missile", "id": 204},
    {"item_name": "Mjolnir Cruise Missile", "id": 202},
    {"item_name": "Nova Cruise Missile", "id": 205},
    {"item_name": "Scourge Cruise Missile", "id": 203},

    {"item_name": "Inferno Torpedo", "id": 2510},
    {"item_name": "Mjolnir Torpedo", "id": 2506},
    {"item_name": "Nova Torpedo", "id": 2508},
    {"item_name": "Scourge Torpedo", "id": 267},

    # Charge
    {"item_name": "Antimatter Charge L", "id": 238},
    {"item_name": "Iridium Charge L", "id": 233},
    {"item_name": "Iron Charge L", "id": 231},
    {"item_name": "Lead Charge L", "id": 234},
    {"item_name": "Plutonium Charge L", "id": 237},
    {"item_name": "Thorium Charge L", "id": 235},
    {"item_name": "Tungsten Charge L", "id": 232},
    {"item_name": "Uranium Charge L", "id": 236},

    {"item_name": "Antimatter Charge M", "id": 230},
    {"item_name": "Iridium Charge M", "id": 225},
    {"item_name": "Iron Charge M", "id": 223},
    {"item_name": "Lead Charge M", "id": 226},
    {"item_name": "Plutonium Charge M", "id": 229},
    {"item_name": "Thorium Charge M", "id": 227},
    {"item_name": "Tungsten Charge M", "id": 224},
    {"item_name": "Uranium Charge M", "id": 228},

    {"item_name": "Antimatter Charge S", "id": 222},
    {"item_name": "Iridium Charge S", "id": 217},
    {"item_name": "Iron Charge S", "id": 215},
    {"item_name": "Lead Charge S", "id": 218},
    {"item_name": "Plutonium Charge S", "id": 221},
    {"item_name": "Thorium Charge S", "id": 219},
    {"item_name": "Tungsten Charge S", "id": 216},
    {"item_name": "Uranium Charge S", "id": 220},

]


#print(items_faction_wars_state_protectorate)

items_faction_wars_state_protectorate = [
    # Shield Extenders
    {"item_name": "Caldari Navy Large Shield Extender",
     "lp_store_components": {"Federation Navy Fleet Colonel Insignia I": 2, "Federation Navy Fleet Colonel Insignia II": 4, "Large Shield Extender I": 1},
     "lp_price": 10000,
     "isk_price": 4000000,
     "quantity": 1,
     "id": 31930},

    {"item_name": "Caldari Navy Medium Shield Extender",
    "lp_store_components": {"Federation Navy Fleet Colonel Insignia I": 2, "Medium Shield Extender I": 1},
    "lp_price": 3000,
    "isk_price": 2000000,
    "quantity": 1,
    "id": 31926},

    {"item_name": "Caldari Navy Small Shield Extender",
     "lp_store_components": {"Federation Navy Command Sergeant Major Insignia I": 2, "Small Shield Extender I": 1, "Federation Navy Fleet Major Insignia I": 4},
     "lp_price": 1000,
     "isk_price": 500000,
     "quantity": 1,
     "id": 31922,},

    # Shield Hardener
    {"item_name": "Caldari Navy Multispectrum Shield Hardener",
     "lp_store_components": {"Federation Navy Fleet Colonel Insignia I": 66, "Federation Navy Fleet Major Insignia I": 15,
                             "Federation Navy Fleet Colonel Insignia II": 98, "Multispectrum Shield Hardener I": 1},
     "lp_price": 180000,
     "isk_price": 72000000,
     "quantity": 1,
     "id": 17498,},

    {"item_name": "Caldari Navy EM Shield Hardener",
     "lp_store_components": {"Federation Navy Fleet Colonel Insignia I": 4, "Federation Navy Fleet Major Insignia I": 2,
                             "Federation Navy Fleet Colonel Insignia II": 6, "EM Shield Hardener I": 1},
     "lp_price": 11250,
     "isk_price": 4500000,
     "quantity": 1,
     "id": 17499,},

    {"item_name": "Caldari Navy Explosive Shield Hardener",
     "lp_store_components": {"Federation Navy Fleet Colonel Insignia I": 4, "Federation Navy Fleet Major Insignia I": 2,
                             "Federation Navy Fleet Colonel Insignia II": 6, "Explosive Shield Hardener I": 1},
     "lp_price": 11250,
     "isk_price": 4500000,
     "quantity": 1,
     "id": 17496, },

    {"item_name": "Caldari Navy Kinetic Shield Hardener",
     "lp_store_components": {"Federation Navy Fleet Colonel Insignia I": 4, "Federation Navy Fleet Major Insignia I": 2,
                             "Federation Navy Fleet Colonel Insignia II": 6, "Kinetic Shield Hardener I": 1},
     "lp_price": 11250,
     "isk_price": 4500000,
     "quantity": 1,
     "id": 17495, },

    {"item_name": "Caldari Navy Thermal Shield Hardener",
     "lp_store_components": {"Federation Navy Fleet Colonel Insignia I": 4, "Federation Navy Fleet Major Insignia I": 2,
                             "Federation Navy Fleet Colonel Insignia II": 6, "Thermal Shield Hardener I": 1},
     "lp_price": 11250,
     "isk_price": 4500000,
     "quantity": 1,
     "id": 17497, },

    # Shield Boosters
    {"item_name": "Caldari Navy Small Shield Booster",
     "lp_store_components": {"Small Shield Booster I": 1, "Federation Navy Sergeant Insignia I": 151,
                             "Federation Navy Sergeant Insignia II": 190, "Federation Navy Sergeant Insignia III": 227},
     "lp_price": 30375,
     "isk_price": 12150000,
     "quantity": 1,
     "id": 15898, },

    {"item_name": "Caldari Navy Medium Shield Booster",
     "lp_store_components": {"Medium Shield Booster I": 1, "Federation Navy Fleet Captain Insignia I": 108,
                             "Federation Navy Fleet Major Insignia I": 178},
     "lp_price": 40500,
     "isk_price": 16200000,
     "quantity": 1,
     "id": 15899, },

    {"item_name": "Caldari Navy Large Shield Booster",
     "lp_store_components": {"Large Shield Booster I": 1, "Federation Navy Fleet Colonel Insignia I": 18,
                             "Federation Navy Fleet Major Insignia I": 3, "Federation Navy Fleet Colonel Insignia II": 28},
     "lp_price": 50625,
     "isk_price": 20250000,
     "quantity": 1,
     "id": 15900, },

    {"item_name": "Caldari Navy X-Large Shield Booster",
     "lp_store_components": {"X-Large Shield Booster I": 1, "Federation Navy Fleet Colonel Insignia I": 22,
                             "Federation Navy Fleet Major Insignia I": 7, "Federation Navy Fleet Colonel Insignia II": 33},
     "lp_price": 60750,
     "isk_price": 24300000,
     "quantity": 1,
     "id": 15897, },

    {"item_name": "Caldari Navy Shield Boost Amplifier",
     "lp_store_components": {"Federation Navy Fleet Colonel Insignia I": 18, "Shield Boost Amplifier I": 1,
                             "Federation Navy Fleet Colonel Insignia II": 28, "Federation Navy Fleet Major Insignia I": 3},
     "lp_price": 50625,
     "isk_price": 20250000,
     "quantity": 1,
     "id": 15905, },

    # Modules
    {"item_name": "Caldari Navy Co-Processor",
     "lp_store_components": {"Co-Processor I": 1, "Federation Navy Fleet Captain Insignia I": 120,
                             "Federation Navy Fleet Major Insignia I": 198},
     "lp_price": 45000,
     "isk_price": 18000000,
     "quantity": 1,
     "id": 15675, },

    {"item_name": "Navy Micro Auxiliary Power Core",
     "lp_store_components": {"Micro Auxiliary Power Core I": 1, "Federation Navy Fleet Colonel Insignia I": 2},
     "lp_price": 1500,
     "isk_price": 1500000,
     "quantity": 1,
     "id": 31936, },

    {"item_name": "Caldari Navy Warp Scrambler",
     "lp_store_components": {"Warp Scrambler I": 1, "Federation Navy Fleet Captain Insignia I": 38,
                             "Federation Navy Fleet Major Insignia I": 61},
     "lp_price": 14000,
     "isk_price": 5600000,
     "quantity": 1,
     "id": 15887, },

    {"item_name": "Caldari Navy Warp Disruptor",
     "lp_store_components": {"Warp Disruptor I": 1, "Federation Navy Fleet Captain Insignia I": 38,
                             "Federation Navy Fleet Major Insignia I": 61},
     "lp_price": 14000,
     "isk_price": 5600000,
     "quantity": 1,
     "id": 15887, },

    {"item_name": "Caldari Navy Stasis Webifier",
     "lp_store_components": {"Stasis Webifier I": 1, "Federation Navy Fleet Colonel Insignia I": 7,
                             "Federation Navy Fleet Major Insignia I": 2, "Federation Navy Fleet Colonel Insignia II": 11},
     "lp_price": 20000,
     "isk_price": 8000000,
     "quantity": 1,
     "id": 17500, },

    {"item_name": "Caldari Navy Cloaking Device",
     "lp_store_components": {"Prototype Cloaking Device I": 1, "Federation Navy Sergeant Insignia I": 59,
                             "Federation Navy Sergeant Insignia II": 74, "Federation Navy Sergeant Insignia III": 91},
     "lp_price": 12000,
     "isk_price": 4800000,
     "quantity": 1,
     "id": 15790, },

    {"item_name": "Caldari Navy Power Diagnostic System",
     "lp_store_components": {"Power Diagnostic System I": 1, "Federation Navy Fleet Colonel Insignia I": 2,
                             "Federation Navy Fleet Colonel Insignia II": 4},
     "lp_price": 10000,
     "isk_price": 4000000,
     "quantity": 1,
     "id": 31952, },

    {"item_name": "Caldari Navy Ballistic Control System",
     "lp_store_components": {"Ballistic Control System I": 1, "Federation Navy Fleet Colonel Insignia I": 17,
                             "Federation Navy Fleet Major Insignia I": 5, "	Federation Navy Fleet Colonel Insignia II": 24},
     "lp_price": 45000,
     "isk_price": 18000000,
     "quantity": 1,
     "id": 15681, },

    # DataCore
    {"item_name": "Datacore - Quantum Physics",
     "lp_store_components": {},
     "lp_price": 250,
     "isk_price": 250000,
     "quantity": 5,
     "id": 20414,},
    {"item_name": "Datacore - Rocket Science",
     "lp_store_components": {},
     "lp_price": 250,
     "isk_price": 250000,
     "quantity": 5,
     "id": 20420,},
    {"item_name": "Datacore - Graviton Physics",
     "lp_store_components": {},
     "lp_price": 250,
     "isk_price": 250000,
     "quantity": 5,
     "id": 20419,},
    {"item_name": "Datacore - Caldari Starship Engineering",
     "lp_store_components": {},
     "lp_price": 250,
     "isk_price": 250000,
     "quantity": 5,
     "id": 25887,},
    {"item_name": "Datacore - Mechanical Engineering",
     "lp_store_components": {},
     "lp_price": 250,
     "isk_price": 250000,
     "quantity": 5,
     "id": 20424,},

    # Cap Booster
    {"item_name": "Navy Cap Booster 25",
     "lp_store_components": {"Cap Booster 25": 20},
     "lp_price": 60,
     "isk_price": 60000,
     "quantity": 20,
     "id": 33330, },
    {"item_name": "Navy Cap Booster 50",
     "lp_store_components": {"Cap Booster 50": 20},
     "lp_price": 125,
     "isk_price": 125000,
     "quantity": 20,
     "id": 33332, },
    {"item_name": "Navy Cap Booster 75",
     "lp_store_components": {"Cap Booster 75": 20},
     "lp_price": 185,
     "isk_price": 185000,
     "quantity": 20,
     "id": 33334, },
    {"item_name": "Navy Cap Booster 150",
     "lp_store_components": {"Cap Booster 150": 20},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 20,
     "id": 31990, },
    {"item_name": "Navy Cap Booster 200",
     "lp_store_components": {"Cap Booster 200": 20},
     "lp_price": 500,
     "isk_price": 500000,
     "quantity": 20,
     "id": 31998, },
    {"item_name": "Navy Cap Booster 400",
     "lp_store_components": {"Cap Booster 400": 20},
     "lp_price": 1000,
     "isk_price": 1000000,
     "quantity": 20,
     "id": 32006, },
    {"item_name": "Navy Cap Booster 800",
     "lp_store_components": {"Cap Booster 800": 20},
     "lp_price": 2000,
     "isk_price": 2000000,
     "quantity": 20,
     "id": 32014, },
    {"item_name": "Navy Cap Booster 3200",
     "lp_store_components": {"Cap Booster 3200": 20},
     "lp_price": 8000,
     "isk_price": 8000000,
     "quantity": 20,
     "id": 41490, },

    # Drones
    {"item_name": "Caldari Navy Hornet",
     "lp_store_components": {"Hornet I": 5},
     "lp_price": 3000,
     "isk_price": 3000000,
     "quantity": 5,
     "id": 31872, },

    {"item_name": "Caldari Navy Vespa",
     "lp_store_components": {"Vespa I": 5},
     "lp_price": 4000,
     "isk_price": 4000000,
     "quantity": 5,
     "id": 31874, },

    {"item_name": "Caldari Navy Wasp",
     "lp_store_components": {"Wasp I": 5},
     "lp_price": 5000,
     "isk_price": 5000000,
     "quantity": 5,
     "id": 31876, },

    # Ships Production
    {"item_name": "Heron Navy Issue (Production)*",
     "lp_store_components": {"Life Support Backup Unit": 5,  "Megacyte": 10, "Auto-Integrity Preservation Seal": 10, "Zydrine": 20, "Nocxium": 30, "Isogen": 500, "Mexallon": 2500, "Pyerite": 6000, "Tritanium": 32000},
     "lp_price": 4000,
     "isk_price": 2000000,
     "production_cost": None,         # Jita: 114к, 2.12% - 28к, FW: 6к
     "quantity": 1,
     "id": 72904, },

    {"item_name": "Caldari Navy Hookbill (Production)",
     "lp_store_components": {"Life Support Backup Unit": 5, "Megacyte": 10, "Auto-Integrity Preservation Seal": 10,
                             "Zydrine": 20, "Nocxium": 30, "Isogen": 500, "Mexallon": 2500, "Pyerite": 6000,
                             "Tritanium": 32000},
     "lp_price": 4000,
     "isk_price": 2000000,
     "production_cost": None,          # Jita: 114к, 2.12% - 28к, FW: 6к
     "quantity": 1,
     "id": 17619, },

    {"item_name": "Griffin Navy Issue (Production)",
     "lp_store_components": {"Life Support Backup Unit": 5, "Megacyte": 10, "Auto-Integrity Preservation Seal": 10,
                             "Zydrine": 20, "Nocxium": 30, "Isogen": 500, "Mexallon": 2500, "Pyerite": 6000,
                             "Tritanium": 32000},
     "lp_price": 4000,
     "isk_price": 2000000,
     "production_cost": None,           # Jita: 114к, 2.12% - 28к, FW: 6к
     "quantity": 1,
     "id": 37455, },

    {"item_name": "Cormorant Navy Issue (Production)",
     "lp_store_components": {"Life Support Backup Unit": 5, "Megacyte": 10, "Auto-Integrity Preservation Seal": 10,
                             "Zydrine": 20, "Nocxium": 30, "Isogen": 1000, "Mexallon": 5000, "Pyerite": 15000,
                             "Tritanium": 80000},
     "lp_price": 12000,
     "isk_price": 3500000,
     "production_cost": None,           # Jita: 197208; 2.12% - 28к; FW: 10к
     "quantity": 1,
     "id": 73795, },

    {"item_name": "Osprey Navy Issue (Production)*",
     "lp_store_components": {"Life Support Backup Unit": 25, "Megacyte": 500, "Auto-Integrity Preservation Seal": 50,
                             "Zydrine": 1000, "Nocxium": 1500, "Isogen": 10000, "Mexallon": 36000, "Pyerite": 180000,
                             "Tritanium": 540000},
     "lp_price": 18000,
     "isk_price": 5000000,
     "production_cost": None,        # Jita: 1972000; 2.12% - 282к; FW: 106к
     "quantity": 1,
     "id": 29340, },

    {"item_name": "Caracal Navy Issue (Production)*",
     "lp_store_components": {"Life Support Backup Unit": 25, "Megacyte": 500, "Auto-Integrity Preservation Seal": 50,
                             "Zydrine": 1000, "Nocxium": 1500, "Isogen": 10000, "Mexallon": 36000, "Pyerite": 180000,
                             "Tritanium": 540000},
     "lp_price": 18000,
     "isk_price": 5000000,
     "production_cost": None,        # Jita: 1972000; 2.12% - 282к; FW: 106к
     "quantity": 1,
     "id": 17634, },

    {"item_name": "Drake Navy Issue (Production)*",
     "lp_store_components": {"Life Support Backup Unit": 50, "Megacyte": 2000, "Auto-Integrity Preservation Seal": 100,
                             "Zydrine": 4000, "Nocxium": 10000, "Isogen": 20000, "Mexallon": 180000, "Pyerite": 1000000,
                             "Tritanium": 2800000},
     "lp_price": 40000,
     "isk_price": 10000000,
     "production_cost": None,
     "quantity": 1,
     "id": 33153, },

    {"item_name": "Ferox Navy Issue (Production)*",
     "lp_store_components": {"Life Support Backup Unit": 50, "Megacyte": 2000, "Auto-Integrity Preservation Seal": 100,
                             "Zydrine": 4000, "Nocxium": 10000, "Isogen": 20000, "Mexallon": 180000, "Pyerite": 1000000,
                             "Tritanium": 2800000},
     "lp_price": 40000,
     "isk_price": 10000000,
     "production_cost": None,
     "quantity": 1,
     "id": 72812, },

    {"item_name": "Scorpion Navy Issue (Production)*",
     "lp_store_components": {"Core Temperature Regulator": 1, "Life Support Backup Unit": 100, "Megacyte": 4000,
                             "Auto-Integrity Preservation Seal": 200, "Zydrine": 8000, "Nocxium": 30000,
                             "Isogen": 400000, "Mexallon": 600000, "Pyerite": 4000000, "Tritanium": 8000000},
     "lp_price": 100000,
     "isk_price": 20000000,
     "production_cost": None,           # Jita: 33.000.000;     HS: 6.730.000
     "quantity": 1,
     "id": 32309, },

    {"item_name": "Raven Navy Issue (Production)*",
     "lp_store_components": {"Core Temperature Regulator": 1, "Life Support Backup Unit": 100, "Megacyte": 4000,
                             "Auto-Integrity Preservation Seal": 200, "Zydrine": 8000, "Nocxium": 30000,
                             "Isogen": 400000, "Mexallon": 600000, "Pyerite": 4000000, "Tritanium": 8000000},
     "lp_price": 100000,
     "isk_price": 20000000,
     "production_cost": None,           # Jita: 33.000.000
     "quantity": 1,
     "id": 17636, },

#    {"item_name": "Phoenix Navy Issue (Production)",
#     "lp_store_components": {"Core Temperature Regulator": 1, "Neurolink Protection Cell": 1, "Capital Sensor Cluster": 2,
#                             "Capital Armor Plates": 2, "Capital Capacitor Battery": 2, "Capital Power Generator": 2,
#                             "Capital Jump Drive": 2, "Capital Construction Parts": 2, "Capital Corporate Hangar Bay": 2,
#                             "Gravimetric-FTL Interlink Communicator": 2, "Capital Computer System": 4,
#                             "Capital Propulsion Engine": 5, "Capital Shield Emitter": 5, "Capital Ship Maintenance Bay": 5,
#                             "R-O Trigger Neurolink Conduit": 16, "Capital Siege Array": 20, "Capital Launcher Hardpoint": 20,
#                             "Life Support Backup Unit": 200, "Auto-Integrity Preservation Seal": 400,},
#     "lp_price": 1000000,
#     "isk_price": 200000000,
#    "production_cost": None,
#    "quantity": 1,
#     "id": 73793, },

    # Launchers
    {"item_name": "Caldari Navy Rapid Light Missile Launcher",
     "lp_store_components": {"Rapid Light Missile Launcher I": 1, "Federation Navy Fleet Captain Insignia I": 63,
                             "Federation Navy Fleet Major Insignia I": 106, },
     "lp_price": 24000,
     "isk_price": 9600000,
     "quantity": 1,
     "id": 16061, },

    {"item_name": "Caldari Navy Rapid Heavy Missile Launcher",
     "lp_store_components": {"Rapid Heavy Missile Launcher I": 1, "Federation Navy Fleet Colonel Insignia I": 10,
                             "Federation Navy Fleet Major Insignia I": 2,
                             "Federation Navy Fleet Colonel Insignia II": 14},
     "lp_price": 26250,
     "isk_price": 10500000,
     "quantity": 1,
     "id": 33446, },

    {"item_name": "Caldari Navy Rapid Heavy Missile Launcher (Prod)*",
     "lp_store_components": {"Federation Navy Fleet Colonel Insignia I": 29, "Federation Navy Fleet Major Insignia I": 5,
                             "Federation Navy Fleet Colonel Insignia II": 43, "Megacyte": 160, "Tritanium": 665,
                             "Pyerite": 7500, "Nocxium": 55, "Zydrine": 20},
     "lp_price": 75000,
     "isk_price": 31500000,
     "quantity": 5,
     "id": 33446, },

    {"item_name": "Caldari Navy Rocket Launcher",
     "lp_store_components": {"Rocket Launcher I": 1, "Federation Navy Sergeant Insignia II": 112,
                             "Federation Navy Sergeant Insignia I": 89, "Federation Navy Sergeant Insignia III": 135},
     "lp_price": 18000,
     "isk_price": 7200000,
     "quantity": 1,
     "id": 16065, },

    {"item_name": "Caldari Navy Rocket Launcher (Production)*",
     "lp_store_components": {"Federation Navy Sergeant Insignia I": 270, "Federation Navy Sergeant Insignia II": 336,
                             "Federation Navy Sergeant Insignia III": 404, "Tritanium": 2780, "Pyerite": 1390},
     "lp_price": 54000,
     "isk_price": 21600000,
     "quantity": 5,
     "id": 16065, },

    {"item_name": "Caldari Navy Cruise Missile Launcher",
     "lp_store_components": {"Cruise Missile Launcher I": 1, "Federation Navy Fleet Colonel Insignia I": 10,
                             "Federation Navy Fleet Major Insignia I": 2, "Federation Navy Fleet Colonel Insignia II": 17},
     "lp_price": 30000,
     "isk_price": 12000000,
     "quantity": 1,
     "id": 16062, },

    {"item_name": "Caldari Navy Cruise Missile Launcher (Production)*",
     "lp_store_components": {"Federation Navy Fleet Colonel Insignia I": 33, "Federation Navy Fleet Major Insignia I": 7,
                             "Federation Navy Fleet Colonel Insignia II": 49, "Megacyte": 110, "Tritanium": 610,
                             "Pyerite": 6710, "Nocxium": 45, "Zydrine": 20},
     "lp_price": 90000,
     "isk_price": 36000000,
     "quantity": 5,
     "id": 16062, },

    {"item_name": "Caldari Navy Light Missile Launcher",
    "lp_store_components": {"Light Missile Launcher I": 1, "Federation Navy Sergeant Insignia II": 112,
                             "Federation Navy Sergeant Insignia III": 135, "Federation Navy Sergeant Insignia I": 89},
     "lp_price": 18000,
     "isk_price": 7200000,
     "quantity": 1,
     "id": 16068, },

    {"item_name": "Caldari Navy Heavy Missile Launcher",
     "lp_store_components": {"Heavy Missile Launcher I": 1, "Federation Navy Fleet Captain Insignia I": 63,
                             "Federation Navy Fleet Major Insignia I": 106},
     "lp_price": 24000,
     "isk_price": 9600000,
     "quantity": 1,
     "id": 16064, },

    {"item_name": "Caldari Navy Torpedo Launcher",
     "lp_store_components": {"Torpedo Launcher I": 1, "Federation Navy Fleet Colonel Insignia I": 10,
                             "Federation Navy Fleet Major Insignia I": 2, "Federation Navy Fleet Colonel Insignia II": 17},
     "lp_price": 30000,
     "isk_price": 12000000,
     "quantity": 1,
     "id": 16067, },

    # SmartBombs
    {"item_name": "Caldari Navy Small Graviton Smartbomb",
     "lp_store_components": {"Small Graviton Smartbomb I": 1, "Federation Navy Sergeant Insignia I": 168,
                             "Federation Navy Sergeant Insignia II": 210, "Federation Navy Sergeant Insignia III": 253},
     "lp_price": 33750,
     "isk_price": 13500000,
     "quantity": 1,
     "id": 15925, },

    {"item_name": "Caldari Navy Small Graviton Smartbomb BluePrint (Production)*",
     "lp_store_components": {"Federation Navy Sergeant Insignia I": 504, "Federation Navy Sergeant Insignia II": 631,
                             "Federation Navy Sergeant Insignia III ": 758, "Tritanium": 30285, "Pyerite": 20210,
                             "Nocxium": 15, "Megacyte": 10},
     "lp_price": 101250,
     "isk_price": 40500000,
     "production_cost": None,        # Jita: ???;     HS: ???
     "quantity": 5,
     "id": 15925, },        # id - Caldari Navy Small Graviton Smartbomb

    {"item_name": "Caldari Navy Medium Graviton Smartbomb",
     "lp_store_components": {"Medium Graviton Smartbomb I": 1, "Federation Navy Fleet Captain Insignia I": 120,
                             "Federation Navy Fleet Major Insignia I": 198},
     "lp_price": 45000,
     "isk_price": 18000000,
     "quantity": 1,
     "id": 15929, },

#    {"item_name": "Caldari Navy Medium Graviton Smartbomb BluePrint (Production)*",
#     "lp_store_components": {"Federation Navy Fleet Captain Insignia I": 358, "Federation Navy Fleet Major Insignia I": 595,
#                             "Tritanium": 77705, "Pyerite": 6590, "Mexallon": 335},
#     "lp_price": 135000,
#     "isk_price": 54000000,
#     "production_cost": None,  # Jita: ???;     HS: ???
#     "quantity": 5,
#     "id": 15929, },        # id - Caldari Navy Medium Graviton Smartbomb

    {"item_name": "Caldari Navy Large Graviton Smartbomb",
     "lp_store_components": {"Large Graviton Smartbomb I": 1, "Federation Navy Fleet Colonel Insignia I": 20,
                             "Federation Navy Fleet Major Insignia I": 5, "Federation Navy Fleet Colonel Insignia II": 31},
     "lp_price": 56250,
     "isk_price": 22500000,
     "quantity": 1,
     "id": 15931, },

#    {"item_name": "Caldari Navy Large Graviton Smartbomb BluePrint (Production)*",
#     "lp_store_components": {"Federation Navy Fleet Major Insignia I": 12, "Federation Navy Fleet Colonel Insignia I": 62,
#                             "Federation Navy Fleet Colonel Insignia II": 92, "Tritanium": 201180, "Pyerite": 166715},
#     "lp_price": 168750,
#     "isk_price": 67500000,
#     "production_cost": None,        # Jita: ???;     HS: ???
#     "quantity": 5,
#     "id": 15931, },        # id - Caldari Navy Large Graviton Smartbomb

    # Missile
    {"item_name": "Caldari Navy Inferno Light Missile",
     "lp_store_components": {"Inferno Light Missile": 5000, },
     "lp_price": 2400,
     "isk_price": 2400000,
     "quantity": 5000,
     "id": 27371, },

    {"item_name": "Caldari Navy Mjolnir Light Missile",
     "lp_store_components": {"Mjolnir Light Missile": 5000, },
     "lp_price": 2400,
     "isk_price": 2400000,
     "quantity": 5000,
     "id": 27387, },

    {"item_name": "Caldari Navy Nova Light Missile",
     "lp_store_components": {"Nova Light Missile": 5000, },
     "lp_price": 2400,
     "isk_price": 2400000,
     "quantity": 5000,
     "id": 27381, },

    {"item_name": "Caldari Navy Scourge Light Missile",
     "lp_store_components": {"Scourge Light Missile": 5000, },
     "lp_price": 2400,
     "isk_price": 2400000,
     "quantity": 5000,
     "id": 27361, },

    {"item_name": "Caldari Navy Inferno Heavy Missile",
     "lp_store_components": {"Inferno Heavy Missile": 5000},
     "lp_price": 3000,
     "isk_price": 3000000,
     "quantity": 5000,
     "id": 27447, },

    {"item_name": "Caldari Navy Mjolnir Heavy Missile",
     "lp_store_components": {"Inferno Heavy Missile": 5000},
     "lp_price": 3000,
     "isk_price": 3000000,
     "quantity": 5000,
     "id": 27435, },

    {"item_name": "Caldari Navy Nova Heavy Missile",
     "lp_store_components": {"Inferno Heavy Missile": 5000},
     "lp_price": 3000,
     "isk_price": 3000000,
     "quantity": 5000,
     "id": 27453, },

    {"item_name": "Caldari Navy Scourge Heavy Missile",
     "lp_store_components": {"Inferno Heavy Missile": 5000},
     "lp_price": 3000,
     "isk_price": 3000000,
     "quantity": 5000,
     "id": 27441, },


    {"item_name": "Caldari Navy Inferno Heavy Assault Missile",
     "lp_store_components": {"Inferno Heavy Assault Missile": 5000},
     "lp_price": 3000,
     "isk_price": 3000000,
     "quantity": 5000,
     "id": 27405, },

    {"item_name": "Caldari Navy Mjolnir Heavy Assault Missile",
     "lp_store_components": {"Mjolnir Heavy Assault Missile": 5000},
     "lp_price": 3000,
     "isk_price": 3000000,
     "quantity": 5000,
     "id": 27419, },

    {"item_name": "Caldari Navy Nova Heavy Assault Missile",
     "lp_store_components": {"Nova Heavy Assault Missile": 5000},
     "lp_price": 3000,
     "isk_price": 3000000,
     "quantity": 5000,
     "id": 27401, },

    {"item_name": "Caldari Navy Scourge Heavy Assault Missile",
     "lp_store_components": {"Scourge Heavy Assault Missile": 5000},
     "lp_price": 3000,
     "isk_price": 3000000,
     "quantity": 5000,
     "id": 27413, },

    {"item_name": "Caldari Navy Inferno Cruise Missile",
     "lp_store_components": {"Inferno Cruise Missile": 5000},
     "lp_price": 4200,
     "isk_price": 4200000,
     "quantity": 5000,
     "id": 27423, },

    {"item_name": "Caldari Navy Mjolnir Cruise Missile",
     "lp_store_components": {"Mjolnir Cruise Missile": 5000},
     "lp_price": 4200,
     "isk_price": 4200000,
     "quantity": 5000,
     "id": 27377, },

    {"item_name": "Caldari Navy Nova Cruise Missile",
     "lp_store_components": {"Nova Cruise Missile": 5000},
     "lp_price": 4200,
     "isk_price": 4200000,
     "quantity": 5000,
     "id": 27429, },

    {"item_name": "Caldari Navy Scourge Cruise Missile",
     "lp_store_components": {"Scourge Cruise Missile": 5000},
     "lp_price": 4200,
     "isk_price": 4200000,
     "quantity": 5000,
     "id": 27395, },


    # Railguns
    {"item_name": "Caldari Navy 425mm Railgun",
     "lp_store_components": {"425mm Railgun I": 1, "Federation Navy Fleet Colonel Insignia I": 10,
                             "Federation Navy Fleet Major Insignia I": 2, "Federation Navy Fleet Colonel Insignia II": 17},
     "lp_price": 30000,
     "isk_price": 1200000,
     "quantity": 1,
     "id": 15817, },

    {"item_name": "Caldari Navy 350mm Railgun",
     "lp_store_components": {"350mm Railgun I": 1, "Federation Navy Fleet Colonel Insignia I": 10,
                             "Federation Navy Fleet Major Insignia I": 2, "Federation Navy Fleet Colonel Insignia II": 17},
     "lp_price": 30000,
     "isk_price": 1200000,
     "quantity": 1,
     "id": 15818, },

    {"item_name": "Caldari Navy Dual 250mm Railgun",
     "lp_store_components": {"Dual 250mm Railgun I": 1, "Federation Navy Fleet Colonel Insignia I": 10,
                             "Federation Navy Fleet Major Insignia I": 2, "Federation Navy Fleet Colonel Insignia II": 17},
     "lp_price": 30000,
     "isk_price": 1200000,
     "quantity": 1,
     "id": 15814, },

    {"item_name": "Caldari Navy 150mm Railgun",
     "lp_store_components": {"150mm Railgun I": 1, "Federation Navy Sergeant Insignia II": 112,
                             "Federation Navy Sergeant Insignia I": 89, "Federation Navy Sergeant Insignia III": 135},
     "lp_price": 18000,
     "isk_price": 7200000,
     "quantity": 1,
     "id": 15823, },

    {"item_name": "Caldari Navy 75mm Railgun",
     "lp_store_components": {"75mm Gatling Rail I": 1, "Federation Navy Sergeant Insignia II": 112,
                             "Federation Navy Sergeant Insignia I": 89, "Federation Navy Sergeant Insignia III": 135},
     "lp_price": 18000,
     "isk_price": 7200000,
     "quantity": 1,
     "id": 15816, },

    {"item_name": "Caldari Navy Dual 150mm Railgun",
     "lp_store_components": {"Dual 150mm Railgun I": 1, "Federation Navy Fleet Captain Insignia I": 63,
                             "Federation Navy Fleet Major Insignia I": 106},
     "lp_price": 24000,
     "isk_price": 9600000,
     "quantity": 1,
     "id": 15815, },

    {"item_name": "Caldari Navy 250mm Railgun",
     "lp_store_components": {"250mm Railgun I": 1, "Federation Navy Fleet Captain Insignia I": 63,
                             "Federation Navy Fleet Major Insignia I": 106},
     "lp_price": 24000,
     "isk_price": 9600000,
     "quantity": 1,
     "id": 15820, },

    {"item_name": "Caldari Navy 125mm Railgun",
     "lp_store_components": {"125mm Railgun I": 1, "Federation Navy Sergeant Insignia II": 112,
                             "Federation Navy Sergeant Insignia I": 89, "Federation Navy Sergeant Insignia III": 135},
     "lp_price": 18000,
     "isk_price": 7200000,
     "quantity": 1,
     "id": 15824, },

    {"item_name": "Caldari Navy 200mm Railgun",
     "lp_store_components": {"200mm Railgun I": 1, "Federation Navy Fleet Captain Insignia I": 63,
                             "Federation Navy Fleet Major Insignia I": 106},
     "lp_price": 24000,
     "isk_price": 9600000,
     "quantity": 1,
     "id": 15821, },

    {"item_name": "Caldari Navy 200mm Railgun BluePrint (Production)*",
     "lp_store_components": {"Federation Navy Fleet Captain Insignia I": 190, "Federation Navy Fleet Major Insignia I": 318},
     "lp_price": 72000,
     "isk_price": 28800000,
     "production_cost": None,       # Jita - ???
     "quantity": 5,
     "id": 15821, },        # id - Caldari Navy 200mm Railgun

    # Torpedos
    {"item_name": "Caldari Navy Inferno Torpedo",
     "lp_store_components": {"Inferno Torpedo": 5000},
     "lp_price": 5500,
     "isk_price": 5500000,
     "quantity": 5000,
     "id": 27351, },

    {"item_name": "Caldari Navy Nova Torpedo",
     "lp_store_components": {"Nova Torpedo": 5000},
     "lp_price": 5500,
     "isk_price": 5500000,
     "quantity": 5000,
     "id": 27359, },

    {"item_name": "Caldari Navy Mjolnir Torpedo",
     "lp_store_components": {"Mjolnir Torpedo": 5000},
     "lp_price": 5500,
     "isk_price": 5500000,
     "quantity": 5000,
     "id": 27339, },

    {"item_name": "Caldari Navy Scourge Torpedo",
     "lp_store_components": {"Scourge Torpedo": 5000},
     "lp_price": 5500,
     "isk_price": 5500000,
     "quantity": 5000,
     "id": 27345, },


    # Charge
    {"item_name": "Caldari Navy Antimatter Charge L",
     "lp_store_components": {"Antimatter Charge L": 5000},
     "lp_price": 2400,
     "isk_price": 2400000,
     "quantity": 5000,
     "id": 21740, },

    {"item_name": "Caldari Navy Iridium Charge L",
     "lp_store_components": {"Iridium Charge L": 5000},
     "lp_price": 2400,
     "isk_price": 2400000,
     "quantity": 5000,
     "id": 23049, },

    {"item_name": "Caldari Navy Iron Charge L",
     "lp_store_components": {"Iron Charge L": 5000},
     "lp_price": 2400,
     "isk_price": 2400000,
     "quantity": 5000,
     "id": 23053, },

    {"item_name": "Caldari Navy Lead Charge L",
     "lp_store_components": {"Lead Charge L": 5000},
     "lp_price": 2400,
     "isk_price": 2400000,
     "quantity": 5000,
     "id": 23047, },

    {"item_name": "Caldari Navy Plutonium Charge L",
     "lp_store_components": {"Plutonium Charge L": 5000},
     "lp_price": 2400,
     "isk_price": 2400000,
     "quantity": 5000,
     "id": 23041, },

    {"item_name": "Caldari Navy Thorium Charge L",
     "lp_store_components": {"Thorium Charge L": 5000},
     "lp_price": 2400,
     "isk_price": 2400000,
     "quantity": 5000,
     "id": 23045, },

    {"item_name": "Caldari Navy Tungsten Charge L",
     "lp_store_components": {"Tungsten Charge L": 5000},
     "lp_price": 2400,
     "isk_price": 2400000,
     "quantity": 5000,
     "id": 23051, },

    {"item_name": "Caldari Navy Uranium Charge L",
     "lp_store_components": {"Uranium Charge L": 5000},
     "lp_price": 2400,
     "isk_price": 2400000,
     "quantity": 5000,
     "id": 23043, },

    {"item_name": "Caldari Navy Antimatter Charge M",
     "lp_store_components": {"Antimatter Charge M": 5000},
     "lp_price": 1600,
     "isk_price": 1600000,
     "quantity": 5000,
     "id": 23025, },

    {"item_name": "Caldari Navy Iridium Charge M",
     "lp_store_components": {"Iridium Charge M": 5000},
     "lp_price": 1600,
     "isk_price": 1600000,
     "quantity": 5000,
     "id": 23035, },

    {"item_name": "Caldari Navy Iron Charge M",
     "lp_store_components": {"Iron Charge M": 5000},
     "lp_price": 1600,
     "isk_price": 1600000,
     "quantity": 5000,
     "id": 23039, },

    {"item_name": "Caldari Navy Lead Charge M",
     "lp_store_components": {"Lead Charge M": 5000},
     "lp_price": 1600,
     "isk_price": 1600000,
     "quantity": 5000,
     "id": 23033, },

    {"item_name": "Caldari Navy Plutonium Charge M",
     "lp_store_components": {"Plutonium Charge M": 5000},
     "lp_price": 1600,
     "isk_price": 1600000,
     "quantity": 5000,
     "id": 23027, },

    {"item_name": "Caldari Navy Thorium Charge M",
     "lp_store_components": {"Thorium Charge M": 5000},
     "lp_price": 1600,
     "isk_price": 1600000,
     "quantity": 5000,
     "id": 23031, },

    {"item_name": "Caldari Navy Tungsten Charge M",
     "lp_store_components": {"Tungsten Charge M": 5000},
     "lp_price": 1600,
     "isk_price": 1600000,
     "quantity": 5000,
     "id": 23037, },

    {"item_name": "Caldari Navy Uranium Charge M",
     "lp_store_components": {"Uranium Charge M": 5000},
     "lp_price": 1600,
     "isk_price": 1600000,
     "quantity": 5000,
     "id": 23029, },

    {"item_name": "Caldari Navy Antimatter Charge S",
     "lp_store_components": {"Antimatter Charge S": 5000},
     "lp_price": 1200,
     "isk_price": 1200000,
     "quantity": 5000,
     "id": 23009, },

    {"item_name": "Caldari Navy Iridium Charge S",
     "lp_store_components": {"Iridium Charge S": 5000},
     "lp_price": 1200,
     "isk_price": 1200000,
     "quantity": 5000,
     "id": 23019, },

    {"item_name": "Caldari Navy Iron Charge S",
     "lp_store_components": {"Iron Charge S": 5000},
     "lp_price": 1200,
     "isk_price": 1200000,
     "quantity": 5000,
     "id": 23023, },

    {"item_name": "Caldari Navy Lead Charge S",
     "lp_store_components": {"Lead Charge S": 5000},
     "lp_price": 1200,
     "isk_price": 1200000,
     "quantity": 5000,
     "id": 23017, },

    {"item_name": "Caldari Navy Plutonium Charge S",
     "lp_store_components": {"Plutonium Charge S": 5000},
     "lp_price": 1200,
     "isk_price": 1200000,
     "quantity": 5000,
     "id": 23011, },

    {"item_name": "Caldari Navy Thorium Charge S",
     "lp_store_components": {"Thorium Charge S": 5000},
     "lp_price": 1200,
     "isk_price": 1200000,
     "quantity": 5000,
     "id": 23015, },

    {"item_name": "Caldari Navy Tungsten Charge S",
     "lp_store_components": {"Tungsten Charge S": 5000},
     "lp_price": 1200,
     "isk_price": 1200000,
     "quantity": 5000,
     "id": 23021, },

    {"item_name": "Caldari Navy Uranium Charge S",
     "lp_store_components": {"Uranium Charge S": 5000},
     "lp_price": 1200,
     "isk_price": 1200000,
     "quantity": 5000,
     "id": 23013, },

    # Implants
    {"item_name": "Zainou 'Gypsy' CPU Management EE-601",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27143, },
    {"item_name": "Zainou 'Gypsy' CPU Management EE-603",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 13216, },
    {"item_name": "Zainou 'Gypsy' CPU Management EE-605",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 27142, },

    {"item_name": "Zainou 'Gnome' Launcher CPU Efficiency LE-601",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27091, },
    {"item_name": "Zainou 'Gnome' Launcher CPU Efficiency LE-603",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 24641, },
    {"item_name": "Zainou 'Gnome' Launcher CPU Efficiency LE-605",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 24642, },

    {"item_name": "Eifyr and Co. 'Gunslinger' Motion Prediction MR-701",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27075, },
    {"item_name": "Eifyr and Co. 'Gunslinger' Motion Prediction MR-703",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 9957, },
    {"item_name": "Eifyr and Co. 'Gunslinger' Motion Prediction MR-705",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 27075, },

    {"item_name": "Zainou 'Deadeye' Rapid Launch RL-1001",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27096, },
    {"item_name": "Zainou 'Deadeye' Rapid Launch RL-1003",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 13249, },
    {"item_name": "Zainou 'Deadeye' Rapid Launch RL-1005",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 24638, },

    {"item_name": "Zainou 'Snapshot' Torpedoes TD-601",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27257, },
    {"item_name": "Zainou 'Snapshot' Torpedoes TD-603",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 13231, },
    {"item_name": "Zainou 'Snapshot' Torpedoes TD-605",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 27256, },

    {"item_name": "Zainou 'Deadeye' Target Navigation Prediction TN-901",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27095, },
    {"item_name": "Zainou 'Deadeye' Target Navigation Prediction TN-903",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 13250, },
    {"item_name": "Zainou 'Deadeye' Target Navigation Prediction TN-905",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 24639, },

    {"item_name": "Zainou 'Deadeye' Guided Missile Precision GP-801",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27094, },
    {"item_name": "Zainou 'Deadeye' Guided Missile Precision GP-803",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 24632, },
    {"item_name": "Zainou 'Deadeye' Guided Missile Precision GP-805",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 24640, },

    {"item_name": "Zainou 'Gypsy' Long Range Targeting LT-801",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27229, },
    {"item_name": "Zainou 'Gypsy' Long Range Targeting LT-803",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 27229, },
    {"item_name": "Zainou 'Gypsy' Long Range Targeting LT-805",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 27227, },

    {"item_name": "Zainou 'Snapshot' Light Missiles LM-901",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27253, },
    {"item_name": "Zainou 'Snapshot' Light Missiles LM-903",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 27108, },
    {"item_name": "Zainou 'Snapshot' Light Missiles LM-905",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 27252, },

    {"item_name": "Zainou 'Snapshot' Heavy Assault Missiles AM-701",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27246, },
    {"item_name": "Zainou 'Snapshot' Heavy Assault Missiles AM-703",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 27109, },
    {"item_name": "Zainou 'Snapshot' Heavy Assault Missiles AM-705",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 27245, },

    {"item_name": "Zainou 'Deadeye' Trajectory Analysis TA-701",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27078, },
    {"item_name": "Zainou 'Deadeye' Trajectory Analysis TA-703",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 13245, },
    {"item_name": "Zainou 'Deadeye' Trajectory Analysis TA-705",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 19697, },

    {"item_name": "Zainou 'Gypsy' Signature Analysis SA-701",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27131, },
    {"item_name": "Zainou 'Gypsy' Signature Analysis SA-703",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 10244, },
    {"item_name": "Zainou 'Gypsy' Signature Analysis SA-705",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 27130, },

    {"item_name": "Zainou 'Snapshot' Heavy Missiles HM-701",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27251, },
    {"item_name": "Zainou 'Snapshot' Heavy Missiles HM-703",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 13229, },
    {"item_name": "Zainou 'Snapshot' Heavy Missiles HM-705",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 27250, },

    {"item_name": "Zainou 'Gnome' Shield Operation SP-901",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27107, },
    {"item_name": "Zainou 'Gnome' Shield Operation SP-903",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 13263, },
    {"item_name": "Zainou 'Gnome' Shield Operation SP-905",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 16248, },

    {"item_name": "Zainou 'Gnome' Shield Management SM-701",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27105, },
    {"item_name": "Zainou 'Gnome' Shield Management SM-703",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 10228, },
    {"item_name": "Zainou 'Gnome' Shield Management SM-705",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 16246, },

    {"item_name": "Zainou 'Deadeye' Large Hybrid Turret LH-1001",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27089, },
    {"item_name": "Zainou 'Deadeye' Large Hybrid Turret LH-1003",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 13218, },
    {"item_name": "Zainou 'Deadeye' Large Hybrid Turret LH-1005",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 19698, },

    {"item_name": "Eifyr and Co. 'Rogue' Navigation NN-601",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27097, },
    {"item_name": "Eifyr and Co. 'Rogue' Navigation NN-603",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 13237, },
    {"item_name": "Eifyr and Co. 'Rogue' Navigation NN-605",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 16003, },

    {"item_name": "Eifyr and Co. 'Rogue' Evasive Maneuvering EM-701",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27099, },
    {"item_name": "Eifyr and Co. 'Rogue' Evasive Maneuvering EM-703",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 13240, },
    {"item_name": "Eifyr and Co. 'Rogue' Evasive Maneuvering EM-705",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 16004, },

    {"item_name": "Eifyr and Co. 'Rogue' Fuel Conservation FC-801",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27098, },
    {"item_name": "Eifyr and Co. 'Rogue' Fuel Conservation FC-803",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 13238, },
    {"item_name": "Eifyr and Co. 'Rogue' Fuel Conservation FC-805",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 16005, },

    {"item_name": "Eifyr and Co. 'Rogue' High Speed Maneuvering HS-901",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27100, },
    {"item_name": "Eifyr and Co. 'Rogue' High Speed Maneuvering HS-903",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 13243, },
    {"item_name": "Eifyr and Co. 'Rogue' High Speed Maneuvering HS-905",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 16006, },

    {"item_name": "Eifyr and Co. 'Alchemist' Neurotoxin Recovery NR-1003",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 25547, },
    {"item_name": "Eifyr and Co. 'Alchemist' Neurotoxin Recovery NR-1005",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 25548, },

    {"item_name": "Inherent Implants 'Squire' Capacitor Management EM-801",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27117, },
    {"item_name": "Inherent Implants 'Squire' Capacitor Management EM-803",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 13259, },
    {"item_name": "Inherent Implants 'Squire' Capacitor Management EM-805",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 27116, },

    {"item_name": "Zainou 'Deadeye' Missile Projection MP-701",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27093, },
    {"item_name": "Zainou 'Deadeye' Missile Projection MP-703",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 13248, },
    {"item_name": "Zainou 'Deadeye' Missile Projection MP-705",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 24637, },

    {"item_name": "Zainou 'Gnome' Weapon Upgrades WU-1001",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27080, },
    {"item_name": "Zainou 'Gnome' Weapon Upgrades WU-1003",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 13252, },
    {"item_name": "Zainou 'Gnome' Weapon Upgrades WU-1005",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 16249, },

    {"item_name": "Zainou 'Deadeye' Medium Hybrid Turret MH-801",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27086, },
    {"item_name": "Zainou 'Deadeye' Medium Hybrid Turret MH-803",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 13221, },
    {"item_name": "Zainou 'Deadeye' Medium Hybrid Turret MH-805",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 19699, },

    {"item_name": "Zainou 'Gypsy' Electronic Warfare EW-901",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27226, },
    {"item_name": "Zainou 'Gypsy' Electronic Warfare EW-903",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 13232, },
    {"item_name": "Zainou 'Gypsy' Electronic Warfare EW-905",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 27225, },

    {"item_name": "Zainou 'Gypsy' Propulsion Jamming PJ-801",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27231, },
    {"item_name": "Zainou 'Gypsy' Propulsion Jamming PJ-803",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 13234, },
    {"item_name": "Zainou 'Gypsy' Propulsion Jamming PJ-805",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 27230, },

    {"item_name": "Zainou 'Snapshot' Rockets RD-901",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27255, },
    {"item_name": "Zainou 'Snapshot' Rockets RD-903",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 13230, },
    {"item_name": "Zainou 'Snapshot' Rockets RD-905",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 27254, },

    {"item_name": "Inherent Implants 'Lancer' Small Energy Turret SE-601",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27082, },
    {"item_name": "Inherent Implants 'Lancer' Small Energy Turret SE-603",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 13223, },
    {"item_name": "Inherent Implants 'Lancer' Small Energy Turret SE-605",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 19691, },

    {"item_name": "Inherent Implants 'Noble' Mechanic MC-801",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27072, },
    {"item_name": "Inherent Implants 'Noble' Mechanic MC-803",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 13257, },
    {"item_name": "Inherent Implants 'Noble' Mechanic MC-805",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 19549, },

    {"item_name": "Zainou 'Gypsy' Sensor Linking SL-901",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27233, },
    {"item_name": "Zainou 'Gypsy' Sensor Linking SL-903",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 13235, },
    {"item_name": "Zainou 'Gypsy' Sensor Linking SL-905",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 27233, },

    {"item_name": "Zainou 'Gypsy' Weapon Disruption WD-901",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27235, },
    {"item_name": "Zainou 'Gypsy' Weapon Disruption WD-903",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 13236, },
    {"item_name": "Zainou 'Gypsy' Weapon Disruption WD-905",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 27235, },

    {"item_name": "Eifyr and Co. 'Alchemist' Neurotoxin Control NC-903",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 25545, },
    {"item_name": "Eifyr and Co. 'Alchemist' Neurotoxin Control NC-905",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 25546, },

    {"item_name": "Eifyr and Co. 'Rogue' Acceleration Control AC-601",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27101, },
    {"item_name": "Eifyr and Co. 'Rogue' Acceleration Control AC-603",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 16008, },
    {"item_name": "Eifyr and Co. 'Rogue' Acceleration Control AC-605",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 16009, },

    {"item_name": "Zainou 'Gypsy' Electronics Upgrades EU-601",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27129, },
    {"item_name": "Zainou 'Gypsy' Electronics Upgrades EU-603",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 13254, },
    {"item_name": "Zainou 'Gypsy' Electronics Upgrades EU-605",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 27128, },

    {"item_name": "Inherent Implants 'Lancer' Controlled Bursts CB-701",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27079, },
    {"item_name": "Inherent Implants 'Lancer' Controlled Bursts CB-703",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 13246, },
    {"item_name": "Inherent Implants 'Lancer' Controlled Bursts CB-705",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 19692, },

    {"item_name": "Inherent Implants 'Lancer' Medium Energy Turret ME-801",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27085, },
    {"item_name": "Inherent Implants 'Lancer' Medium Energy Turret ME-803",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 13220, },
    {"item_name": "Inherent Implants 'Lancer' Medium Energy Turret ME-805",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 19695, },

    {"item_name": "Inherent Implants 'Noble' Remote Armor Repair Systems RA-701",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27071, },
    {"item_name": "Inherent Implants 'Noble' Remote Armor Repair Systems RA-703",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 17871, },
    {"item_name": "Inherent Implants 'Noble' Remote Armor Repair Systems RA-705",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 19548, },

    {"item_name": "Inherent Implants 'Noble' Hull Upgrades HG-1001",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27074, },
    {"item_name": "Inherent Implants 'Noble' Hull Upgrades HG-1003",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 13256, },
    {"item_name": "Inherent Implants 'Noble' Hull Upgrades HG-1005",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 19550, },

    {"item_name": "Implants 'Noble' Repair Proficiency RP-901",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27073, },
    {"item_name": "Implants 'Noble' Repair Proficiency RP-903",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 19684, },
    {"item_name": "Implants 'Noble' Repair Proficiency RP-905",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 19685, },

    {"item_name": "Zainou 'Deadeye' Sharpshooter ST-901",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27076, },
    {"item_name": "Zainou 'Deadeye' Sharpshooter ST-903",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 10204, },
    {"item_name": "Zainou 'Deadeye' Sharpshooter ST-905",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 19696, },

    {"item_name": "Inherent Implants 'Lancer' Large Energy Turret LE-1001",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27088, },
    {"item_name": "Inherent Implants 'Lancer' Large Energy Turret LE-1003",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 13217, },
    {"item_name": "Inherent Implants 'Lancer' Large Energy Turret LE-1005",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 19694, },

    {"item_name": "Inherent Implants 'Noble' Repair Systems RS-601",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27070, },
    {"item_name": "Inherent Implants 'Noble' Repair Systems RS-603",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 13258, },
    {"item_name": "Inherent Implants 'Noble' Repair Systems RS-605",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 19547, },

    {"item_name": "Eifyr and Co. 'Gunslinger' Surgical Strike SS-901",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27081, },
    {"item_name": "Eifyr and Co. 'Gunslinger' Surgical Strike SS-903",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 13244, },
    {"item_name": "Eifyr and Co. 'Gunslinger' Surgical Strike SS-905",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 19687, },

    {"item_name": "Eifyr and Co. 'Gunslinger' Large Projectile Turret LP-1001",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27090, },
    {"item_name": "Eifyr and Co. 'Gunslinger' Large Projectile Turret LP-1003",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 13219, },
    {"item_name": "Eifyr and Co. 'Gunslinger' Large Projectile Turret LP-1005",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 19688, },

    {"item_name": "Zainou 'Deadeye' Small Hybrid Turret SH-601",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27083, },
    {"item_name": "Zainou 'Deadeye' Small Hybrid Turret SH-603",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 13224, },
    {"item_name": "Zainou 'Deadeye' Small Hybrid Turret SH-605",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 19700, },

    {"item_name": "Eifyr and Co. 'Gunslinger' Small Projectile Turret SP-601",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27084, },
    {"item_name": "Eifyr and Co. 'Gunslinger' Small Projectile Turret SP-603",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 13225, },
    {"item_name": "Eifyr and Co. 'Gunslinger' Small Projectile Turret SP-605",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 19690, },

    {"item_name": "Eifyr and Co. 'Rogue' Afterburner AB-602",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27111, },
    {"item_name": "Eifyr and Co. 'Rogue' Afterburner AB-606",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 13239, },
    {"item_name": "Eifyr and Co. 'Rogue' Afterburner AB-610",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 27110, },

    {"item_name": "Inherent Implants 'Lancer' Gunnery RF-901",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27077, },
    {"item_name": "Inherent Implants 'Lancer' Gunnery RF-903",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 13166, },
    {"item_name": "Inherent Implants 'Lancer' Gunnery RF-905",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 19693, },

    {"item_name": "Inherent Implants 'Squire' Capacitor Emission Systems ES-701",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27120, },
    {"item_name": "Inherent Implants 'Squire' Capacitor Emission Systems ES-703",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 13265, },
    {"item_name": "Inherent Implants 'Squire' Capacitor Emission Systems ES-705",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 27121, },

    {"item_name": "Inherent Implants 'Squire' Power Grid Management EG-601",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27127, },
    {"item_name": "Inherent Implants 'Squire' Power Grid Management EG-603",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 13261, },
    {"item_name": "Inherent Implants 'Squire' Power Grid Management EG-605",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 27126, },

    {"item_name": "Eifyr and Co. 'Alchemist' Biology BY-805",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27147, },
    {"item_name": "Eifyr and Co. 'Alchemist' Biology BY-810",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 27148, },

    {"item_name": "Zainou 'Snapshot' Cruise Missiles CM-601",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27259, },
    {"item_name": "Zainou 'Snapshot' Cruise Missiles CM-603",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 13226, },
    {"item_name": "Zainou 'Snapshot' Cruise Missiles CM-605",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 27258, },

    {"item_name": "Zainou 'Deadeye' Missile Bombardment MB-701",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27092, },
    {"item_name": "Zainou 'Deadeye' Missile Bombardment MB-703",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 13247, },
    {"item_name": "Zainou 'Deadeye' Missile Bombardment MB-705",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 27092, },

    {"item_name": "Inherent Implants 'Squire' Energy Grid Upgrades EU-701",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27125, },
    {"item_name": "Inherent Implants 'Squire' Energy Grid Upgrades EU-703",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 13255, },
    {"item_name": "Inherent Implants 'Squire' Energy Grid Upgrades EU-705",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 27124, },

    {"item_name": "Inherent Implants 'Squire' Energy Pulse Weapons EP-701",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27123, },
    {"item_name": "Inherent Implants 'Squire' Energy Pulse Weapons EP-703",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 13251, },
    {"item_name": "Inherent Implants 'Squire' Energy Pulse Weapons EP-705",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 27122, },

    {"item_name": "Eifyr and Co. 'Gunslinger' Medium Projectile Turret MP-801",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27087, },
    {"item_name": "Eifyr and Co. 'Gunslinger' Medium Projectile Turret MP-803",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 13222, },
    {"item_name": "Eifyr and Co. 'Gunslinger' Medium Projectile Turret MP-805",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 19689, },

    {"item_name": "Inherent Implants 'Squire' Capacitor Systems Operation EO-601",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27119, },
    {"item_name": "Inherent Implants 'Squire' Capacitor Systems Operation EO-603",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 13260, },
    {"item_name": "Inherent Implants 'Squire' Capacitor Systems Operation EO-605",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 27118, },

    {"item_name": "Zainou 'Gnome' Shield Upgrades SU-601",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27104, },
    {"item_name": "Zainou 'Gnome' Shield Upgrades SU-603",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 13253, },
    {"item_name": "Zainou 'Gnome' Shield Upgrades SU-605",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 16245, },

    {"item_name": "Zainou 'Gnome' Shield Emission Systems SE-801",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27106, },
    {"item_name": "Zainou 'Gnome' Shield Emission Systems SE-803",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 13262, },
    {"item_name": "Zainou 'Gnome' Shield Emission Systems SE-805",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 16247, },

    {"item_name": "Zainou 'Gypsy' Target Painting TG-901",
     "lp_store_components": {},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 1,
     "id": 27237, },
    {"item_name": "Zainou 'Gypsy' Target Painting TG-903",
     "lp_store_components": {},
     "lp_price": 10875,
     "isk_price": 10875000,
     "quantity": 1,
     "id": 27224, },
    {"item_name": "Zainou 'Gypsy' Target Painting TG-905",
     "lp_store_components": {},
     "lp_price": 79375,
     "isk_price": 79375000,
     "quantity": 1,
     "id": 27236, },

    {"item_name": "Limited Memory Augmentation",
     "lp_store_components": {},
     "lp_price": 750,
     "isk_price": 750000,
     "quantity": 1,
     "id": 13284, },
    {"item_name": "Memory Augmentation - Basic",
     "lp_store_components": {},
     "lp_price": 5250,
     "isk_price": 5250000,
     "quantity": 1,
     "id": 9941, },
    {"item_name": "Memory Augmentation - Standard",
     "lp_store_components": {},
     "lp_price": 12000,
     "isk_price": 12000000,
     "quantity": 1,
     "id": 10208, },
    {"item_name": "Memory Augmentation - Improved",
     "lp_store_components": {},
     "lp_price": 65000,
     "isk_price": 65000000,
     "quantity": 1,
     "id": 10209, },

    {"item_name": "Limited Social Adaptation Chip",
     "lp_store_components": {},
     "lp_price": 750,
     "isk_price": 750000,
     "quantity": 1,
     "id": 13286, },
    {"item_name": "Social Adaptation Chip - Basic",
     "lp_store_components": {},
     "lp_price": 5250,
     "isk_price": 5250000,
     "quantity": 1,
     "id": 9956, },
    {"item_name": "Social Adaptation Chip - Standard",
     "lp_store_components": {},
     "lp_price": 12000,
     "isk_price": 12000000,
     "quantity": 1,
     "id": 10225, },
    {"item_name": "Social Adaptation Chip - Improved",
     "lp_store_components": {},
     "lp_price": 65000,
     "isk_price": 65000000,
     "quantity": 1,
     "id": 10226, },

    {"item_name": "Limited Cybernetic Subprocessor",
     "lp_store_components": {},
     "lp_price": 750,
     "isk_price": 750000,
     "quantity": 1,
     "id": 13287, },
    {"item_name": "Cybernetic Subprocessor - Basic",
     "lp_store_components": {},
     "lp_price": 5250,
     "isk_price": 5250000,
     "quantity": 1,
     "id": 9943, },
    {"item_name": "Cybernetic Subprocessor - Standard",
     "lp_store_components": {},
     "lp_price": 12000,
     "isk_price": 12000000,
     "quantity": 1,
     "id": 10221, },
    {"item_name": "Cybernetic Subprocessor - Improved",
     "lp_store_components": {},
     "lp_price": 65000,
     "isk_price": 65000000,
     "quantity": 1,
     "id": 10222, },

    {"item_name": "Limited Ocular Filter",
     "lp_store_components": {},
     "lp_price": 750,
     "isk_price": 750000,
     "quantity": 1,
     "id": 13283, },
    {"item_name": "Ocular Filter - Basic",
     "lp_store_components": {},
     "lp_price": 5250,
     "isk_price": 5250000,
     "quantity": 1,
     "id": 9899, },
    {"item_name": "Ocular Filter - Standard",
     "lp_store_components": {},
     "lp_price": 12000,
     "isk_price": 12000000,
     "quantity": 1,
     "id": 10216, },
    {"item_name": "Ocular Filter - Improved",
     "lp_store_components": {},
     "lp_price": 65000,
     "isk_price": 65000000,
     "quantity": 1,
     "id": 10217, },

    {"item_name": "Limited Neural Boost",
     "lp_store_components": {},
     "lp_price": 750,
     "isk_price": 750000,
     "quantity": 1,
     "id": 13285, },
    {"item_name": "Neural Boost - Basic",
     "lp_store_components": {},
     "lp_price": 5250,
     "isk_price": 5250000,
     "quantity": 1,
     "id": 9942, },
    {"item_name": "Neural Boost - Standard",
     "lp_store_components": {},
     "lp_price": 12000,
     "isk_price": 12000000,
     "quantity": 1,
     "id": 10212, },
    {"item_name": "Neural Boost - Improved",
     "lp_store_components": {},
     "lp_price": 65000,
     "isk_price": 65000000,
     "quantity": 1,
     "id": 10213, },

    # Specialization Books
    {"item_name": "Light Missile Specialization",
     "lp_store_components": {},
     "lp_price": 1000,
     "isk_price": 0,
     "quantity": 1,
     "id": 20210, },
    {"item_name": "Rocket Specialization",
     "lp_store_components": {},
     "lp_price": 1000,
     "isk_price": 0,
     "quantity": 1,
     "id": 20209, },
    {"item_name": "Caldari Drone Specialization",
     "lp_store_components": {},
     "lp_price": 3000,
     "isk_price": 0,
     "quantity": 1,
     "id": 12487, },
    {"item_name": "Heavy Missile Specialization",
     "lp_store_components": {},
     "lp_price": 3000,
     "isk_price": 0,
     "quantity": 1,
     "id": 20211, },
    {"item_name": "Heavy Assault Missile Specialization",
     "lp_store_components": {},
     "lp_price": 3000,
     "isk_price": 0,
     "quantity": 1,
     "id": 25718, },
    {"item_name": "Torpedo Specialization",
     "lp_store_components": {},
     "lp_price": 9000,
     "isk_price": 0,
     "quantity": 1,
     "id": 20213, },
    {"item_name": "Cruise Missile Specialization",
     "lp_store_components": {},
     "lp_price": 9000,
     "isk_price": 0,
     "quantity": 1,
     "id": 20212, },

]


#for item in items_faction_wars_state_protectorate:
#    for component, quantity in item["lp_store_components"].items():
#        print(f"Component: {component}, Quantity: {quantity}")
