items_component = [
    # Tags
    {"item_name": "Federation Navy Fleet Colonel Insignia I", "id": 15594},
    {"item_name": "Federation Navy Fleet Colonel Insignia II", "id": 15673},

    {"item_name": "Federation Navy Command Sergeant Major Insignia I", "id": 15646},
    {"item_name": "Federation Navy Fleet Major Insignia I", "id": 15593},

    {"item_name": "Dread Guristas Gold Tag", "id": 17248},

    # Shield Extenders
    {"item_name": "Large Shield Extender I", "id": 3839},
    {"item_name": "Medium Shield Extender I", "id": 3829},
    {"item_name": "Small Shield Extender I", "id": 377},

    {"item_name": "Cap Booster 25", "id": 263},
    {"item_name": "Cap Booster 50", "id": 264},
    {"item_name": "Cap Booster 75", "id": 3552},
    {"item_name": "Cap Booster 100", "id": 3554},
    {"item_name": "Cap Booster 150", "id": 11283},
    {"item_name": "Cap Booster 200", "id": 11285},
    {"item_name": "Cap Booster 400", "id": 11287},
    {"item_name": "Cap Booster 800", "id": 11289},
    {"item_name": "Cap Booster 3200", "id": 41489},

    # Resourсes
    {"item_name": "Megacyte", "id": 40},
    {"item_name": "Zydrine", "id":39},
    {"item_name": "Nocxium", "id":38},
    {"item_name": "Isogen", "id":37},
    {"item_name": "Mexallon", "id":36},
    {"item_name": "Pyerite", "id":35},
    {"item_name": "Tritanium", "id":34},
    {"item_name": "Auto-Integrity Preservation Seal", "id": 57478},
    {"item_name": "Life Support Backup Unit", "id": 57486},
#    {"item_name": "Core Temperature Regulator", "id": 57479},

    # Components
    {"item_name": "Core Temperature Regulator", "id": 57479},
    {"item_name": "Neurolink Protection Cell", "id": 57488},
    {"item_name": "Capital Sensor Cluster", "id": 21013},
    {"item_name": "Capital Armor Plates", "id": 21017},
    {"item_name": "Capital Capacitor Battery", "id": 21019},
    {"item_name": "Capital Power Generator", "id": 21021},
    {"item_name": "Capital Jump Drive", "id": 21025},
    {"item_name": "Capital Construction Parts", "id": 21037},
    {"item_name": "Capital Corporate Hangar Bay", "id": 24560},
    {"item_name": "Gravimetric-FTL Interlink Communicator", "id": 57475},
    {"item_name": "Capital Computer System", "id": 21035},
    {"item_name": "Capital Propulsion Engine", "id": 21009},
    {"item_name": "Capital Shield Emitter", "id": 21023},
    {"item_name": "Capital Ship Maintenance Bay", "id": 24558},
    {"item_name": "R-O Trigger Neurolink Conduit", "id": 57471},
    {"item_name": "Capital Siege Array", "id": 21039},
    {"item_name": "Capital Launcher Hardpoint", "id": 21041},

    # Missile
    {"item_name": "Inferno Light Missile", "id": 211},
    {"item_name": "Mjolnir Light Missile", "id": 212},
    {"item_name": "Nova Light Missile", "id": 213},
    {"item_name": "Scourge Light Missile", "id": 210},

    {"item_name": "Inferno Heavy Missile", "id": 208},
    {"item_name": "Mjolnir Heavy Missile", "id": 207},
    {"item_name": "Nova Heavy Missile", "id": 206},
    {"item_name": "Scourge Heavy Missile", "id": 209},

    {"item_name": "Inferno Heavy Missile", "id": 20308},
    {"item_name": "Mjolnir Heavy Assault Missile", "id": 20306},
    {"item_name": "Nova Heavy Assault Missile", "id": 21867},
    {"item_name": "Scourge Heavy Assault Missile", "id": 20307},

    {"item_name": "Inferno Cruise Missile", "id": 204},
    {"item_name": "Mjolnir Cruise Missile", "id": 202},
    {"item_name": "Nova Cruise Missile", "id": 205},
    {"item_name": "Scourge Cruise Missile", "id": 203},

    {"item_name": "Inferno Torpedo", "id": 2510},
    {"item_name": "Mjolnir Torpedo", "id": 2506},
    {"item_name": "Nova Torpedo", "id": 2508},
    {"item_name": "Scourge Torpedo", "id": 267},

]


#print(items_faction_wars_state_protectorate)

items_faction_wars_state_protectorate = [
    # Shield Extenders
    {"item_name": "Caldari Navy Large Shield Extender",
     "lp_store_components": {"Federation Navy Fleet Colonel Insignia I": 2, "Federation Navy Fleet Colonel Insignia II": 4, "Large Shield Extender I": 1},
     "lp_price": 10000,
     "isk_price": 4000000,
     "quantity": 1,
     "id": 31930},

    {"item_name": "Caldari Navy Medium Shield Extender",
    "lp_store_components": {"Federation Navy Fleet Colonel Insignia I": 2, "Medium Shield Extender I": 1},
    "lp_price": 3000,
    "isk_price": 2000000,
    "quantity": 1,
    "id": 31926},

    {"item_name": "Caldari Navy Small Shield Extender",
     "lp_store_components": {"Federation Navy Command Sergeant Major Insignia I": 2, "Small Shield Extender I": 1, "Federation Navy Fleet Major Insignia I": 4},
     "lp_price": 1000,
     "isk_price": 500000,
     "quantity": 1,
     "id": 31922,},

    # DataCore
    {"item_name": "Datacore - Quantum Physics",
     "lp_store_components": {},
     "lp_price": 250,
     "isk_price": 250000,
     "quantity": 5,
     "id": 20414,},
    {"item_name": "Datacore - Rocket Science",
     "lp_store_components": {},
     "lp_price": 250,
     "isk_price": 250000,
     "quantity": 5,
     "id": 20420,},
    {"item_name": "Datacore - Graviton Physics",
     "lp_store_components": {},
     "lp_price": 250,
     "isk_price": 250000,
     "quantity": 5,
     "id": 20419,},
    {"item_name": "Datacore - Caldari Starship Engineering",
     "lp_store_components": {},
     "lp_price": 250,
     "isk_price": 250000,
     "quantity": 5,
     "id": 25887,},
    {"item_name": "Datacore - Mechanical Engineering",
     "lp_store_components": {},
     "lp_price": 250,
     "isk_price": 250000,
     "quantity": 5,
     "id": 20424,},

    # Cap Booster
    {"item_name": "Navy Cap Booster 25",
     "lp_store_components": {"Cap Booster 25": 20},
     "lp_price": 60,
     "isk_price": 60000,
     "quantity": 20,
     "id": 33330, },
    {"item_name": "Navy Cap Booster 50",
     "lp_store_components": {"Cap Booster 50": 20},
     "lp_price": 125,
     "isk_price": 125000,
     "quantity": 20,
     "id": 33332, },
    {"item_name": "Navy Cap Booster 75",
     "lp_store_components": {"Cap Booster 75": 20},
     "lp_price": 185,
     "isk_price": 185000,
     "quantity": 20,
     "id": 33334, },
    {"item_name": "Navy Cap Booster 150",
     "lp_store_components": {"Cap Booster 150": 20},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 20,
     "id": 31990, },
    {"item_name": "Navy Cap Booster 200",
     "lp_store_components": {"Cap Booster 200": 20},
     "lp_price": 500,
     "isk_price": 500000,
     "quantity": 20,
     "id": 31998, },
    {"item_name": "Navy Cap Booster 400",
     "lp_store_components": {"Cap Booster 400": 20},
     "lp_price": 1000,
     "isk_price": 1000000,
     "quantity": 20,
     "id": 32006, },
    {"item_name": "Navy Cap Booster 800",
     "lp_store_components": {"Cap Booster 800": 20},
     "lp_price": 2000,
     "isk_price": 2000000,
     "quantity": 20,
     "id": 32014, },
    {"item_name": "Navy Cap Booster 3200",
     "lp_store_components": {"Cap Booster 3200": 20},
     "lp_price": 8000,
     "isk_price": 8000000,
     "quantity": 20,
     "id": 41490, },

    # Ships Production
    {"item_name": "Heron Navy Issue (Production)",
     "lp_store_components": {"Life Support Backup Unit": 5,  "Megacyte": 10, "Auto-Integrity Preservation Seal": 10, "Zydrine": 20, "Nocxium": 30, "Isogen": 500, "Mexallon": 2500, "Pyerite": 6000, "Tritanium": 32000},
     "lp_price": 4000,
     "isk_price": 2000000,
     "production_cost": 114000,
     "quantity": 1,
     "id": 72904, },

    {"item_name": "Caldari Navy Hookbill (Production)",
     "lp_store_components": {"Life Support Backup Unit": 5, "Megacyte": 10, "Auto-Integrity Preservation Seal": 10,
                             "Zydrine": 20, "Nocxium": 30, "Isogen": 500, "Mexallon": 2500, "Pyerite": 6000,
                             "Tritanium": 32000},
     "lp_price": 4000,
     "isk_price": 2000000,
     "production_cost": 114000,
     "quantity": 1,
     "id": 17619, },

    {"item_name": "Griffin Navy Issue (Production)",
     "lp_store_components": {"Life Support Backup Unit": 5, "Megacyte": 10, "Auto-Integrity Preservation Seal": 10,
                             "Zydrine": 20, "Nocxium": 30, "Isogen": 500, "Mexallon": 2500, "Pyerite": 6000,
                             "Tritanium": 32000},
     "lp_price": 4000,
     "isk_price": 2000000,
     "production_cost": 114500,
     "quantity": 1,
     "id": 37455, },

    {"item_name": "Cormorant Navy Issue (Production)",
     "lp_store_components": {"Life Support Backup Unit": 5, "Megacyte": 10, "Auto-Integrity Preservation Seal": 10,
                             "Zydrine": 20, "Nocxium": 30, "Isogen": 1000, "Mexallon": 5000, "Pyerite": 15000,
                             "Tritanium": 80000},
     "lp_price": 12000,
     "isk_price": 3500000,
     "production_cost": 197208,
     "quantity": 1,
     "id": 73795, },

    {"item_name": "Osprey Navy Issue (Production)",
     "lp_store_components": {"Life Support Backup Unit": 25, "Megacyte": 500, "Auto-Integrity Preservation Seal": 50,
                             "Zydrine": 1000, "Nocxium": 1500, "Isogen": 10000, "Mexallon": 36000, "Pyerite": 180000,
                             "Tritanium": 540000},
     "lp_price": 18000,
     "isk_price": 5000000,
     "production_cost": 1972000,
     "quantity": 1,
     "id": 29340, },

    {"item_name": "Caracal Navy Issue (Production)",
     "lp_store_components": {"Life Support Backup Unit": 25, "Megacyte": 500, "Auto-Integrity Preservation Seal": 50,
                             "Zydrine": 1000, "Nocxium": 1500, "Isogen": 10000, "Mexallon": 36000, "Pyerite": 180000,
                             "Tritanium": 540000},
     "lp_price": 18000,
     "isk_price": 5000000,
     "production_cost": 1972000,
     "quantity": 1,
     "id": 17634, },

    {"item_name": "Drake Navy Issue (Production)",
     "lp_store_components": {"Life Support Backup Unit": 50, "Megacyte": 2000, "Auto-Integrity Preservation Seal": 100,
                             "Zydrine": 4000, "Nocxium": 10000, "Isogen": 20000, "Mexallon": 180000, "Pyerite": 1000000,
                             "Tritanium": 2800000},
     "lp_price": 40000,
     "isk_price": 10000000,
     "production_cost": None,
     "quantity": 1,
     "id": 33153, },

    {"item_name": "Ferox Navy Issue (Production)",
     "lp_store_components": {"Life Support Backup Unit": 50, "Megacyte": 2000, "Auto-Integrity Preservation Seal": 100,
                             "Zydrine": 4000, "Nocxium": 10000, "Isogen": 20000, "Mexallon": 180000, "Pyerite": 1000000,
                             "Tritanium": 2800000},
     "lp_price": 40000,
     "isk_price": 10000000,
     "production_cost": None,
     "quantity": 1,
     "id": 72812, },

    {"item_name": "Scorpion Navy Issue (Production)",
     "lp_store_components": {"Core Temperature Regulator": 1, "Life Support Backup Unit": 100, "Megacyte": 4000,
                             "Auto-Integrity Preservation Seal": 200, "Zydrine": 8000, "Nocxium": 30000,
                             "Isogen": 400000, "Mexallon": 600000, "Pyerite": 4000000, "Tritanium": 8000000},
     "lp_price": 100000,
     "isk_price": 20000000,
     "production_cost": None,
     "quantity": 1,
     "id": 32309, },

    {"item_name": "Raven Navy Issue (Production)",
     "lp_store_components": {"Core Temperature Regulator": 1, "Life Support Backup Unit": 100, "Megacyte": 4000,
                             "Auto-Integrity Preservation Seal": 200, "Zydrine": 8000, "Nocxium": 30000,
                             "Isogen": 400000, "Mexallon": 600000, "Pyerite": 4000000, "Tritanium": 8000000},
     "lp_price": 100000,
     "isk_price": 20000000,
     "production_cost": None,
     "quantity": 1,
     "id": 17636, },

#    {"item_name": "Phoenix Navy Issue (Production)",
#     "lp_store_components": {"Core Temperature Regulator": 1, "Neurolink Protection Cell": 1, "Capital Sensor Cluster": 2,
#                             "Capital Armor Plates": 2, "Capital Capacitor Battery": 2, "Capital Power Generator": 2,
#                             "Capital Jump Drive": 2, "Capital Construction Parts": 2, "Capital Corporate Hangar Bay": 2,
#                             "Gravimetric-FTL Interlink Communicator": 2, "Capital Computer System": 4,
#                             "Capital Propulsion Engine": 5, "Capital Shield Emitter": 5, "Capital Ship Maintenance Bay": 5,
#                             "R-O Trigger Neurolink Conduit": 16, "Capital Siege Array": 20, "Capital Launcher Hardpoint": 20,
#                             "Life Support Backup Unit": 200, "Auto-Integrity Preservation Seal": 400,},
#     "lp_price": 1000000,
#     "isk_price": 200000000,
#    "production_cost": None,
#    "quantity": 1,
#     "id": 73793, },


    # Missile
    {"item_name": "Caldari Navy Inferno Light Missile",
     "lp_store_components": {"Inferno Light Missile": 5000, },
     "lp_price": 2400,
     "isk_price": 2400000,
     "quantity": 5000,
     "id": 27371, },

    {"item_name": "Caldari Navy Mjolnir Light Missile",
     "lp_store_components": {"Mjolnir Light Missile": 5000, },
     "lp_price": 2400,
     "isk_price": 2400000,
     "quantity": 5000,
     "id": 27387, },

    {"item_name": "Caldari Navy Nova Light Missile",
     "lp_store_components": {"Nova Light Missile": 5000, },
     "lp_price": 2400,
     "isk_price": 2400000,
     "quantity": 5000,
     "id": 27381, },

    {"item_name": "Caldari Navy Scourge Light Missile",
     "lp_store_components": {"Scourge Light Missile": 5000, },
     "lp_price": 2400,
     "isk_price": 2400000,
     "quantity": 5000,
     "id": 27361, },

    {"item_name": "Caldari Navy Inferno Heavy Missile",
     "lp_store_components": {"Inferno Heavy Missile": 5000},
     "lp_price": 3000,
     "isk_price": 3000000,
     "quantity": 5000,
     "id": 27447, },

    {"item_name": "Caldari Navy Mjolnir Heavy Missile",
     "lp_store_components": {"Inferno Heavy Missile": 5000},
     "lp_price": 3000,
     "isk_price": 3000000,
     "quantity": 5000,
     "id": 27435, },

    {"item_name": "Caldari Navy Nova Heavy Missile",
     "lp_store_components": {"Inferno Heavy Missile": 5000},
     "lp_price": 3000,
     "isk_price": 3000000,
     "quantity": 5000,
     "id": 27453, },

    {"item_name": "Caldari Navy Scourge Heavy Missile",
     "lp_store_components": {"Inferno Heavy Missile": 5000},
     "lp_price": 3000,
     "isk_price": 3000000,
     "quantity": 5000,
     "id": 27441, },


    {"item_name": "Caldari Navy Inferno Heavy Assault Missile",
     "lp_store_components": {"Inferno Heavy Assault Missile": 5000},
     "lp_price": 3000,
     "isk_price": 3000000,
     "quantity": 5000,
     "id": 27405, },

    {"item_name": "Caldari Navy Mjolnir Heavy Assault Missile",
     "lp_store_components": {"Mjolnir Heavy Assault Missile": 5000},
     "lp_price": 3000,
     "isk_price": 3000000,
     "quantity": 5000,
     "id": 27419, },

    {"item_name": "Caldari Navy Nova Heavy Assault Missile",
     "lp_store_components": {"Nova Heavy Assault Missile": 5000},
     "lp_price": 3000,
     "isk_price": 3000000,
     "quantity": 5000,
     "id": 27401, },

    {"item_name": "Caldari Navy Scourge Heavy Assault Missile",
     "lp_store_components": {"Scourge Heavy Assault Missile": 5000},
     "lp_price": 3000,
     "isk_price": 3000000,
     "quantity": 5000,
     "id": 27413, },

    {"item_name": "Caldari Navy Inferno Cruise Missile",
     "lp_store_components": {"Inferno Cruise Missile": 5000},
     "lp_price": 4200,
     "isk_price": 4200000,
     "quantity": 5000,
     "id": 27423, },

    {"item_name": "Caldari Navy Mjolnir Cruise Missile",
     "lp_store_components": {"Mjolnir Cruise Missile": 5000},
     "lp_price": 4200,
     "isk_price": 4200000,
     "quantity": 5000,
     "id": 27377, },

    {"item_name": "Caldari Navy Nova Cruise Missile",
     "lp_store_components": {"Nova Cruise Missile": 5000},
     "lp_price": 4200,
     "isk_price": 4200000,
     "quantity": 5000,
     "id": 27429, },

    {"item_name": "Caldari Navy Scourge Cruise Missile",
     "lp_store_components": {"Scourge Cruise Missile": 5000},
     "lp_price": 4200,
     "isk_price": 4200000,
     "quantity": 5000,
     "id": 27395, },


    {"item_name": "Caldari Navy Inferno Torpedo",
     "lp_store_components": {"Inferno Torpedo": 5000},
     "lp_price": 5500,
     "isk_price": 5500000,
     "quantity": 5000,
     "id": 27351, },

    {"item_name": "Caldari Navy Nova Torpedo",
     "lp_store_components": {"Nova Torpedo": 5000},
     "lp_price": 5500,
     "isk_price": 5500000,
     "quantity": 5000,
     "id": 27359, },

    {"item_name": "Caldari Navy Mjolnir Torpedo",
     "lp_store_components": {"Mjolnir Torpedo": 5000},
     "lp_price": 5500,
     "isk_price": 5500000,
     "quantity": 5000,
     "id": 27339, },

    {"item_name": "Caldari Navy Scourge Torpedo",
     "lp_store_components": {"Scourge Torpedo": 5000},
     "lp_price": 5500,
     "isk_price": 5500000,
     "quantity": 5000,
     "id": 27345, },

]


#for item in items_faction_wars_state_protectorate:
#    for component, quantity in item["lp_store_components"].items():
#        print(f"Component: {component}, Quantity: {quantity}")
