# Переменная с кораблями.
# Некоторых кораблей, который выходили в последних обновления в переменной нет. Нужно добавить

items_ships = [
    {'group_name': 'None', 'name': 'Bantam', 'id': 582},
    {'group_name': 'None', 'name': 'Condor', 'id': 583},
    {'group_name': 'None', 'name': 'Griffin', 'id': 584},
    {'group_name': 'None', 'name': 'Slasher', 'id': 585},
    {'group_name': 'None', 'name': 'Probe', 'id': 586},
    {'group_name': 'None', 'name': 'Rifter', 'id': 587},
    {'group_name': 'None', 'name': 'Reaper', 'id': 588},
    {'group_name': 'None', 'name': 'Executioner', 'id': 589},
    {'group_name': 'None', 'name': 'Inquisitor', 'id': 590},
    {'group_name': 'None', 'name': 'Tormentor', 'id': 591},
    {'group_name': 'None', 'name': 'Navitas', 'id': 592},
    {'group_name': 'None', 'name': 'Tristan', 'id': 593},
    {'group_name': 'None', 'name': 'Incursus', 'id': 594},
    {'group_name': 'None', 'name': 'Gallente Police Ship', 'id': 595},
    {'group_name': 'None', 'name': 'Impairor', 'id': 596},
    {'group_name': 'None', 'name': 'Punisher', 'id': 597},
    {'group_name': 'None', 'name': 'Breacher', 'id': 598},
    {'group_name': 'None', 'name': 'Burst', 'id': 599},
    {'group_name': 'None', 'name': 'Minmatar Peacekeeper Ship', 'id': 600},
    {'group_name': 'None', 'name': 'Ibis', 'id': 601},
    {'group_name': 'None', 'name': 'Kestrel', 'id': 602},
    {'group_name': 'None', 'name': 'Merlin', 'id': 603},
    {'group_name': 'None', 'name': 'Heron', 'id': 605},
    {'group_name': 'None', 'name': 'Velator', 'id': 606},
    {'group_name': 'None', 'name': 'Imicus', 'id': 607},
    {'group_name': 'None', 'name': 'Atron', 'id': 608},
    {'group_name': 'None', 'name': 'Maulus', 'id': 609},
    {'group_name': 'None', 'name': 'Devourer', 'id': 613},
    {'group_name': 'None', 'name': 'Fury', 'id': 614},
    {'group_name': 'None', 'name': 'Immolator', 'id': 615},
    {'group_name': 'None', 'name': 'Medusa', 'id': 616},
    {'group_name': 'None', 'name': 'Echo', 'id': 617},
    {'group_name': 'None', 'name': 'Lynx', 'id': 618},
    {'group_name': 'None', 'name': 'Swordspine', 'id': 619},
    {'group_name': 'None', 'name': 'Osprey', 'id': 620},
    {'group_name': 'None', 'name': 'Caracal', 'id': 621},
    {'group_name': 'None', 'name': 'Stabber', 'id': 622},
    {'group_name': 'None', 'name': 'Moa', 'id': 623},
    {'group_name': 'None', 'name': 'Maller', 'id': 624},
    {'group_name': 'None', 'name': 'Augoror', 'id': 625},
    {'group_name': 'None', 'name': 'Vexor', 'id': 626},
    {'group_name': 'None', 'name': 'Thorax', 'id': 627},
    {'group_name': 'None', 'name': 'Arbitrator', 'id': 628},
    {'group_name': 'None', 'name': 'Rupture', 'id': 629},
    {'group_name': 'None', 'name': 'Bellicose', 'id': 630},
    {'group_name': 'None', 'name': 'Scythe', 'id': 631},
    {'group_name': 'None', 'name': 'Blackbird', 'id': 632},
    {'group_name': 'None', 'name': 'Celestis', 'id': 633},
    {'group_name': 'None', 'name': 'Exequror', 'id': 634},
    {'group_name': 'None', 'name': 'Opux Luxury Yacht', 'id': 635},
    {'group_name': 'None', 'name': 'Raven', 'id': 638},
    {'group_name': 'None', 'name': 'Tempest', 'id': 639},
    {'group_name': 'None', 'name': 'Scorpion', 'id': 640},
    {'group_name': 'None', 'name': 'Megathron', 'id': 641},
    {'group_name': 'None', 'name': 'Apocalypse', 'id': 642},
    {'group_name': 'None', 'name': 'Armageddon', 'id': 643},
    {'group_name': 'None', 'name': 'Typhoon', 'id': 644},
    {'group_name': 'None', 'name': 'Dominix', 'id': 645},
    {'group_name': 'None', 'name': 'Badger', 'id': 648},
    {'group_name': 'None', 'name': 'Tayra', 'id': 649},
    {'group_name': 'None', 'name': 'Nereus', 'id': 650},
    {'group_name': 'None', 'name': 'Hoarder', 'id': 651},
    {'group_name': 'None', 'name': 'Mammoth', 'id': 652},
    {'group_name': 'None', 'name': 'Wreathe', 'id': 653},
    {'group_name': 'None', 'name': 'Kryos', 'id': 654},
    {'group_name': 'None', 'name': 'Epithal', 'id': 655},
    {'group_name': 'None', 'name': 'Miasmos', 'id': 656},
    {'group_name': 'None', 'name': 'Iteron Mark V', 'id': 657},
    {'group_name': 'None', 'name': 'Capsule', 'id': 670},
    {'group_name': 'None', 'name': 'Erebus', 'id': 671},

    {'group_name': 'None', 'name': 'Bestower', 'id': 1944},

    {'group_name': 'None', 'name': 'Primae', 'id': 2863},

    {'group_name': 'None', 'name': 'Noctis', 'id': 2998},

    {'group_name': 'None', 'name': 'Revenant', 'id': 3514},
    {'group_name': 'None', 'name': 'Malice', 'id': 3516},
    {'group_name': 'None', 'name': 'Vangel', 'id': 3518},

    {'group_name': 'None', 'name': 'Gnosis', 'id': 3756},

    {'group_name': 'None', 'name': 'Leviathan', 'id': 3764},
    {'group_name': 'None', 'name': 'Vigil', 'id': 3766},

    {'group_name': 'None', 'name': 'Helios', 'id': 11172},
    {'group_name': 'None', 'name': 'Keres', 'id': 11174},
    {'group_name': 'None', 'name': 'Crow', 'id': 11176},
    {'group_name': 'None', 'name': 'Raptor', 'id': 11178},
    {'group_name': 'None', 'name': 'Cheetah', 'id': 11182},
    {'group_name': 'None', 'name': 'Crusader', 'id': 11184},
    {'group_name': 'None', 'name': 'Malediction', 'id': 11186},
    {'group_name': 'None', 'name': 'Anathema', 'id': 11188},
    {'group_name': 'None', 'name': 'Sentinel', 'id': 11190},
    {'group_name': 'None', 'name': 'Buzzard', 'id': 11192},
    {'group_name': 'None', 'name': 'Kitsune', 'id': 11194},
    {'group_name': 'None', 'name': 'Claw', 'id': 11196},
    {'group_name': 'None', 'name': 'Stiletto', 'id': 11198},
    {'group_name': 'None', 'name': 'Taranis', 'id': 11200},
    {'group_name': 'None', 'name': 'Ares', 'id': 11202},

    {'group_name': 'None', 'name': 'Vengeance', 'id': 11365},

    {'group_name': 'None', 'name': 'Wolf', 'id': 11371},
    {'group_name': 'None', 'name': 'Blade', 'id': 11373},
    {'group_name': 'None', 'name': 'Erinye', 'id': 11375},
    {'group_name': 'None', 'name': 'Nemesis', 'id': 11377},
    {'group_name': 'None', 'name': 'Hawk', 'id': 11379},
    {'group_name': 'None', 'name': 'Harpy', 'id': 11381},
    {'group_name': 'None', 'name': 'Gatherer', 'id': 11383},
    {'group_name': 'None', 'name': 'Hyena', 'id': 11387},
    {'group_name': 'None', 'name': 'Kishar', 'id': 11389},
    {'group_name': 'None', 'name': 'Retribution', 'id': 11393},
    {'group_name': 'None', 'name': 'Jaguar', 'id': 11400},

    {'group_name': 'None', 'name': 'Gold Magnate', 'id': 11940},
    {'group_name': 'None', 'name': 'Silver Magnate', 'id': 11942},

    {'group_name': 'None', 'name': 'Falcon', 'id': 11957},
    {'group_name': 'None', 'name': 'Rook', 'id': 11959},
    {'group_name': 'None', 'name': 'Huginn', 'id': 11961},
    {'group_name': 'None', 'name': 'Rapier', 'id': 11963},
    {'group_name': 'None', 'name': 'Pilgrim', 'id': 11965},
    {'group_name': 'None', 'name': 'Arazu', 'id': 11969},
    {'group_name': 'None', 'name': 'Lachesis', 'id': 11971},
    {'group_name': 'None', 'name': 'Scimitar', 'id': 11978},
    {'group_name': 'None', 'name': 'Basilisk', 'id': 11985},
    {'group_name': 'None', 'name': 'Guardian', 'id': 11987},
    {'group_name': 'None', 'name': 'Oneiros', 'id': 11989},
    {'group_name': 'None', 'name': 'Cerberus', 'id': 11993},
    {'group_name': 'None', 'name': 'Onyx', 'id': 11995},
    {'group_name': 'None', 'name': 'Vagabond', 'id': 11999},
    {'group_name': 'None', 'name': 'Zealot', 'id': 12003},
    {'group_name': 'None', 'name': 'Ishtar', 'id': 12005},
    {'group_name': 'None', 'name': 'Eagle', 'id': 12011},
    {'group_name': 'None', 'name': 'Broadsword', 'id': 12013},
    {'group_name': 'None', 'name': 'Muninn', 'id': 12015},
    {'group_name': 'None', 'name': 'Devoter', 'id': 12017},
    {'group_name': 'None', 'name': 'Sacrilege', 'id': 12019},
    {'group_name': 'None', 'name': 'Phobos', 'id': 12021},
    {'group_name': 'None', 'name': 'Deimos', 'id': 12023},
    {'group_name': 'None', 'name': 'Manticore', 'id': 12032},
    {'group_name': 'None', 'name': 'Hound', 'id': 12034},
    {'group_name': 'None', 'name': 'Dagger', 'id': 12036},
    {'group_name': 'None', 'name': 'Purifier', 'id': 12038},
    {'group_name': 'None', 'name': 'Ishkur', 'id': 12042},
    {'group_name': 'None', 'name': 'Enyo', 'id': 12044},

    {'group_name': 'None', 'name': 'Crane', 'id': 12729},
    {'group_name': 'None', 'name': 'Bustard', 'id': 12731},
    {'group_name': 'None', 'name': 'Prorator', 'id': 12733},
    {'group_name': 'None', 'name': 'Prowler', 'id': 12735},
    {'group_name': 'None', 'name': 'Viator', 'id': 12743},
    {'group_name': 'None', 'name': 'Occator', 'id': 12745},
    {'group_name': 'None', 'name': 'Mastodon', 'id': 12747},
    {'group_name': 'None', 'name': 'Impel', 'id': 12753},

    {'group_name': 'None', 'name': 'Ferox', 'id': 16227},
    {'group_name': 'None', 'name': 'Brutix', 'id': 16229},
    {'group_name': 'None', 'name': 'Cyclone', 'id': 16231},
    {'group_name': 'None', 'name': 'Prophecy', 'id': 16233},
    {'group_name': 'None', 'name': 'Coercer', 'id': 16236},
    {'group_name': 'None', 'name': 'Cormorant', 'id': 16238},
    {'group_name': 'None', 'name': 'Catalyst', 'id': 16240},
    {'group_name': 'None', 'name': 'Thrasher', 'id': 16242},

    {'group_name': 'None', 'name': 'Covetor', 'id': 17476},
    {'group_name': 'None', 'name': 'Retriever', 'id': 17478},
    {'group_name': 'None', 'name': 'Procurer', 'id': 17480},

    {'group_name': 'None', 'name': 'Caracal Navy Issue', 'id': 17634},
    {'group_name': 'None', 'name': 'Raven Navy Issue', 'id': 17636},

    {'group_name': 'None', 'name': 'Imperial Navy Slicer', 'id': 17703},
    {'group_name': 'None', 'name': 'Khanid Navy Frigate', 'id': 17705},
    {'group_name': 'None', 'name': 'Mordus Frigate', 'id': 17707},
    {'group_name': 'None', 'name': 'Omen Navy Issue', 'id': 17709},
    {'group_name': 'None', 'name': 'Stabber Fleet Issue', 'id': 17713},
    {'group_name': 'None', 'name': 'Gila', 'id': 17715},
    {'group_name': 'None', 'name': 'Phantasm', 'id': 17718},
    {'group_name': 'None', 'name': 'Cynabal', 'id': 17720},
    {'group_name': 'None', 'name': 'Vigilant', 'id': 17722},
    {'group_name': 'None', 'name': 'Apocalypse Navy Issue', 'id': 17726},
    {'group_name': 'None', 'name': 'Megathron Navy Issue', 'id': 17728},
    {'group_name': 'None', 'name': 'Tempest Fleet Issue', 'id': 17732},
    {'group_name': 'None', 'name': 'Nightmare', 'id': 17736},
    {'group_name': 'None', 'name': 'Machariel', 'id': 17738},
    {'group_name': 'None', 'name': 'Vindicator', 'id': 17740},

    {'group_name': 'None', 'name': 'Republic Fleet Firetail', 'id': 17812},

    {'group_name': 'None', 'name': 'Federation Navy Comet', 'id': 17841},
    {'group_name': 'None', 'name': 'Vexor Navy Issue', 'id': 17843},

    {'group_name': 'None', 'name': 'Rattlesnake', 'id': 17918},
    {'group_name': 'None', 'name': 'Bhaalgorn', 'id': 17920},
    {'group_name': 'None', 'name': 'Ashimmu', 'id': 17922},
    {'group_name': 'None', 'name': 'Succubus', 'id': 17924},
    {'group_name': 'None', 'name': 'Cruor', 'id': 17926},
    {'group_name': 'None', 'name': 'Daredevil', 'id': 17928},
    {'group_name': 'None', 'name': 'Worm', 'id': 17930},
    {'group_name': 'None', 'name': 'Dramiel', 'id': 17932},

    {'group_name': 'None', 'name': 'Revelation', 'id': 19720},
    {'group_name': 'None', 'name': 'Naglfar', 'id': 19722},
    {'group_name': 'None', 'name': 'Moros', 'id': 19724},
    {'group_name': 'None', 'name': 'Phoenix', 'id': 19726},

    {'group_name': 'None', 'name': 'Sigil', 'id': 19744},

    {'group_name': 'None', 'name': 'Curse', 'id': 20125},

    {'group_name': 'None', 'name': 'Providence', 'id': 20183},
    {'group_name': 'None', 'name': 'Charon', 'id': 20185},
    {'group_name': 'None', 'name': 'Obelisk', 'id': 20187},
    {'group_name': 'None', 'name': 'Fenrir', 'id': 20189},

    {'group_name': 'None', 'name': 'Redeemer', 'id': 22428},
    {'group_name': 'None', 'name': 'Sin', 'id': 22430},
    {'group_name': 'None', 'name': 'Widow', 'id': 22436},
    {'group_name': 'None', 'name': 'Panther', 'id': 22440},
    {'group_name': 'None', 'name': 'Eos', 'id': 22442},
    {'group_name': 'None', 'name': 'Sleipnir', 'id': 22444},
    {'group_name': 'None', 'name': 'Vulture', 'id': 22446},
    {'group_name': 'None', 'name': 'Absolution', 'id': 22448},
    {'group_name': 'None', 'name': 'Heretic', 'id': 22452},
    {'group_name': 'None', 'name': 'Sabre', 'id': 22456},
    {'group_name': 'None', 'name': 'Eris', 'id': 22460},
    {'group_name': 'None', 'name': 'Flycatcher', 'id': 22464},
    {'group_name': 'None', 'name': 'Astarte', 'id': 22466},
    {'group_name': 'None', 'name': 'Claymore', 'id': 22468},
    {'group_name': 'None', 'name': 'Nighthawk', 'id': 22470},
    {'group_name': 'None', 'name': 'Damnation', 'id': 22474},

    {'group_name': 'None', 'name': 'Hulk', 'id': 22544},
    {'group_name': 'None', 'name': 'Skiff', 'id': 22546},
    {'group_name': 'None', 'name': 'Mackinaw', 'id': 22548},

    {'group_name': 'None', 'name': 'Nidhoggur', 'id': 24483},

    {'group_name': 'None', 'name': 'Archon', 'id': 23757},

    {'group_name': 'None', 'name': 'Ragnarok', 'id': 23773},

    {'group_name': 'None', 'name': 'Hel', 'id': 22852},

    {'group_name': 'None', 'name': 'Thanatos', 'id': 23911},
    {'group_name': 'None', 'name': 'Nyx', 'id': 23913},
    {'group_name': 'None', 'name': 'Chimera', 'id': 23915},
    {'group_name': 'None', 'name': 'Wyvern', 'id': 23917},
    {'group_name': 'None', 'name': 'Aeon', 'id': 23919},

    {'group_name': 'None', 'name': 'Rokh', 'id': 24688},
    {'group_name': 'None', 'name': 'Hyperion', 'id': 24690},
    {'group_name': 'None', 'name': 'Abaddon', 'id': 24692},
    {'group_name': 'None', 'name': 'Maelstrom', 'id': 24694},
    {'group_name': 'None', 'name': 'Harbinger', 'id': 24696},
    {'group_name': 'None', 'name': 'Drake', 'id': 24698},
    {'group_name': 'None', 'name': 'Myrmidon', 'id': 24700},
    {'group_name': 'None', 'name': 'Hurricane', 'id': 24702},

    {'group_name': 'None', 'name': 'Rorqual', 'id': 28352},
    {'group_name': 'None', 'name': 'Orca', 'id': 28606},

    {'group_name': 'None', 'name': 'Paladin', 'id': 28659},
    {'group_name': 'None', 'name': 'Kronos', 'id': 28661},
    {'group_name': 'None', 'name': 'Vargur', 'id': 28665},
    {'group_name': 'None', 'name': 'Golem', 'id': 28710},

    {'group_name': 'None', 'name': 'Rhea', 'id': 28844},
    {'group_name': 'None', 'name': 'Nomad', 'id': 28846},
    {'group_name': 'None', 'name': 'Anshar', 'id': 28848},
    {'group_name': 'None', 'name': 'Ark', 'id': 28850},

    {'group_name': 'None', 'name': 'Apotheosis', 'id': 29266},

    {'group_name': 'None', 'name': 'Scythe Fleet Issue', 'id': 29336},
    {'group_name': 'None', 'name': 'Augoror Navy Issue', 'id': 29337},
    {'group_name': 'None', 'name': 'Osprey Navy Issue', 'id': 29340},
    {'group_name': 'None', 'name': 'Exequror Navy Issue', 'id': 29344},

    {'group_name': 'None', 'name': 'Tengu', 'id': 29984},
    {'group_name': 'None', 'name': 'Legion', 'id': 29986},
    {'group_name': 'None', 'name': 'Proteus', 'id': 29988},
    {'group_name': 'None', 'name': 'Loki', 'id': 29990},

    {'group_name': 'None', 'name': 'Brutix Navy Issue', 'id': 33151},
    {'group_name': 'None', 'name': 'Drake Navy Issue', 'id': 33153},
    {'group_name': 'None', 'name': 'Harbinger Navy Issue', 'id': 33155},
    {'group_name': 'None', 'name': 'Hurricane Fleet Issue', 'id': 33157},

    {'group_name': 'None', 'name': 'Armageddon Navy Issue', 'id': 32305},
    {'group_name': 'None', 'name': 'Dominix Navy Issue', 'id': 32307},
    {'group_name': 'None', 'name': 'Scorpion Navy Issue', 'id': 32309},
    {'group_name': 'None', 'name': 'Typhoon Fleet Issue', 'id': 32311},

    {'group_name': 'None', 'name': 'Venture', 'id': 32880},

    {'group_name': 'None', 'name': 'Astero', 'id': 33468},
    {'group_name': 'None', 'name': 'Stratios', 'id': 33470},
    {'group_name': 'None', 'name': 'Nestor', 'id': 33472},

    {'group_name': 'None', 'name': 'Prospect', 'id': 33697},

    {'group_name': 'None', 'name': 'Garmur', 'id': 33816},
    {'group_name': 'None', 'name': 'Orthrus', 'id': 33818},
    {'group_name': 'None', 'name': 'Barghest', 'id': 33820},

    {'group_name': 'None', 'name': 'Confessor', 'id': 34317},
    {'group_name': 'None', 'name': 'Bowhead', 'id': 34328},

    {'group_name': 'None', 'name': 'Council Diplomatic Shuttle', 'id': 34496},

    {'group_name': 'None', 'name': 'Svipul', 'id': 34562},

    {'group_name': 'None', 'name': 'Jackdaw', 'id': 34828},
    {'group_name': 'None', 'name': 'Hecate', 'id': 35683},

    {'group_name': 'None', 'name': 'Endurance', 'id': 37135},

    {'group_name': 'None', 'name': 'Crucifier Navy Issue', 'id': 37453},
    {'group_name': 'None', 'name': 'Vigil Fleet Issue', 'id': 37454},
    {'group_name': 'None', 'name': 'Griffin Navy Issue', 'id': 37455},
    {'group_name': 'None', 'name': 'Maulus Navy Issue', 'id': 37456},
    {'group_name': 'None', 'name': 'Deacon', 'id': 37457},
    {'group_name': 'None', 'name': 'Kirin', 'id': 37458},
    {'group_name': 'None', 'name': 'Thalia', 'id': 37459},
    {'group_name': 'None', 'name': 'Scalpel', 'id': 37460},
    {'group_name': 'None', 'name': 'Bifrost', 'id': 37480},
    {'group_name': 'None', 'name': 'Pontifex', 'id': 37481},
    {'group_name': 'None', 'name': 'Stork', 'id': 37482},
    {'group_name': 'None', 'name': 'Magus', 'id': 37483},

    {'group_name': 'None', 'name': 'Apostle', 'id': 37604},
    {'group_name': 'None', 'name': 'Minokawa', 'id': 37605},
    {'group_name': 'None', 'name': 'Lif', 'id': 37606},
    {'group_name': 'None', 'name': 'Ninazu', 'id': 37607},

    {'group_name': 'None', 'name': 'Vehement', 'id': 42124},
    {'group_name': 'None', 'name': 'Vendetta', 'id': 42125},
    {'group_name': 'None', 'name': 'Vanquisher', 'id': 42126},
    {'group_name': 'None', 'name': 'Vanguard', 'id': 42132},
    {'group_name': 'None', 'name': 'Venerable', 'id': 42133},

    {'group_name': 'None', 'name': 'Molok', 'id': 42241},
    {'group_name': 'None', 'name': 'Dagon', 'id': 42242},
    {'group_name': 'None', 'name': 'Chemosh', 'id': 42243},
    {'group_name': 'None', 'name': 'Porpoise', 'id': 42244},
    {'group_name': 'None', 'name': 'Rabisu', 'id': 42245},
    {'group_name': 'None', 'name': 'Caedes', 'id': 42246},

    {'group_name': 'None', 'name': 'Sunesis', 'id': 42685},

    {'group_name': 'None', 'name': 'Pacifier', 'id': 44993},
    {'group_name': 'None', 'name': 'Enforcer', 'id': 44995},
    {'group_name': 'None', 'name': 'Marshal', 'id': 44996},
    {'group_name': 'None', 'name': 'Monitor', 'id': 45534},

    {'group_name': 'None', 'name': 'Loggerhead', 'id': 45645},
    {'group_name': 'None', 'name': 'Caiman', 'id': 45647},
    {'group_name': 'None', 'name': 'Komodo', 'id': 45649},

    {'group_name': 'None', 'name': 'Damavik', 'id': 47269},
    {'group_name': 'None', 'name': 'Vedmak', 'id': 47270},
    {'group_name': 'None', 'name': 'Leshak', 'id': 47271},

    {'group_name': 'None', 'name': 'Praxis', 'id': 47466},

    {'group_name': 'None', 'name': 'Kikimora', 'id': 49710},
    {'group_name': 'None', 'name': 'Drekavac', 'id': 49711},
    {'group_name': 'None', 'name': 'Rodiva', 'id': 49712},
    {'group_name': 'None', 'name': 'Zarmazd', 'id': 49713},

    {'group_name': 'None', 'name': 'Avatar', 'id': 50097},

    {'group_name': 'None', 'name': 'Nergal', 'id': 52250},
    {'group_name': 'None', 'name': 'Ikitursa', 'id': 52252},
    {'group_name': 'None', 'name': 'Draugur', 'id': 52254},

    {'group_name': 'None', 'name': 'Skybreaker', 'id': 54731},
    {'group_name': 'None', 'name': 'Stormbringer', 'id': 54732},
    {'group_name': 'None', 'name': 'Thunderchild', 'id': 54733},

    {'group_name': 'None', 'name': 'Cyclone Fleet Issue', 'id': 72811},
    {'group_name': 'None', 'name': 'Ferox Navy Issue', 'id': 72812},
    {'group_name': 'None', 'name': 'Myrmidon Navy Issue', 'id': 72869},
    {'group_name': 'None', 'name': 'Prophecy Navy Issue', 'id': 72872},

    {'group_name': 'None', 'name': 'Probe Fleet Issue', 'id': 72903},
    {'group_name': 'None', 'name': 'Heron Navy Issue', 'id': 72904},
    {'group_name': 'None', 'name': 'Magnate Navy Issue', 'id': 72907},
    {'group_name': 'None', 'name': 'Imicus Navy Issue', 'id': 72913},

    {'group_name': 'None', 'name': 'Naglfar Fleet Issue', 'id': 73787},
    {'group_name': 'None', 'name': 'Coercer Navy Issue', 'id': 73789},
    {'group_name': 'None', 'name': 'Revelation Navy Issue', 'id': 73790},
    {'group_name': 'None', 'name': 'Moros Navy Issue', 'id': 73792},
    {'group_name': 'None', 'name': 'Phoenix Navy Issue', 'id': 73793},
    {'group_name': 'None', 'name': 'Thrasher Fleet Issue', 'id': 73794},
    {'group_name': 'None', 'name': 'Cormorant Navy Issue', 'id': 73795},
    {'group_name': 'None', 'name': 'Catalyst Navy Issue', 'id': 73796},

]

print(f"Total Ships: {len(items_ships)}")
