# Файл с названиеми модулей

items_modules = [
    # Multispectrum Shield Hardeners
    {"id": 2281, "name": "Multispectum Shield Hardener II"},
    {"id": 17498, "name": "Caldari Navy Multispectum Shield Hardener"},
    {"id": 13998, "name": "Domination Multispectum Shield Hardener I"},
    {"id": 13969, "name": "Dread Guristas Multispectum Shield Hardener"},
    {"id": 20637, "name": "'Posse' Multispectum Shield Hardener I"},
    {"id": 4346, "name": "Gistum A-Type Multispectum Shield Hardener"},
    {"id": 4345, "name": "Gistum B-Type Multispectum Shield Hardener"},
    {"id": 2050, "name": "Gistum C-Type Multispectum Shield Hardener"},
    {"id": 4347, "name": "Pithum A-Type Multispectum Shield Hardener"},
    {"id": 4348, "name": "Pithum B-Type Multispectum Shield Hardener"},
    {"id": 4349, "name": "Pithum C-Type Multispectum Shield Hardener"},
    {"id": 14767, "name": "Estamel's Modified Multispectum Shield Hardener"},
    {"id": 14764, "name": "Kaikka's Modified Multispectum Shield Hardener"},
    {"id": 14765, "name": "Thon's Modified Multispectum Shield Hardener"},
    {"id": 14766, "name": "Vepas' Modified Multispectum Shield Hardener"},

    # EM Shield Hardeners
    {"id": 2301, "name": "EM Shield Hardener II"},
    {"id": 20639, "name": "'Poacher' EM Shield Hardener"},
    {"id": 17499, "name": "Caldari Navy EM Shield Hardener"},
    {"id": 13994, "name": "Domination EM Shield Hardener"},
    {"id": 13965, "name": "Dread Guristas EM Shield Hardener"},
    {"id": 19279, "name": "Gist A-Type EM Shield Hardener"},
    {"id": 19265, "name": "Gist B-Type EM Shield Hardener"},
    {"id": 19263, "name": "Gist C-Type EM Shield Hardener"},
    {"id": 19281, "name": "Gist X-Type EM Shield Hardener"},
    {"id": 19280, "name": "Pith A-Type EM Shield Hardener"},
    {"id": 19266, "name": "Pith B-Type EM Shield Hardener"},
    {"id": 19264, "name": "Pith C-Type EM Shield Hardener"},
    {"id": 19282, "name": "Pith X-Type EM Shield Hardener"},
    {"id": 14755, "name": "Estamel's Modified EM Shield Hardener"},
    {"id": 14752, "name": "Kaikka's Modified EM Shield Hardener"},
    {"id": 14753, "name": "Thon's Modified EM Shield Hardener"},
    {"id": 14754, "name": "Vepas' Modified EM Shield Hardener"},

    # Explosive Shield Hardeners
    {"id": 2297, "name": "Explosive Shield Hardener II"},
    {"id": 20641, "name": "'Snake Eyes' Explosive Shield Hardener"},
    {"id": 17496, "name": "Caldari Navy Explosive Shield Hardener"},
    {"id": 13996, "name": "Domination Explosive Shield Hardener"},
    {"id": 13967, "name": "Dread Guristas Explosive Shield Hardener"},
    {"id": 19275, "name": "Gist A-Type Explosive Shield Hardener"},
    {"id": 19269, "name": "Gist B-Type Explosive Shield Hardener"},
    {"id": 19259, "name": "Gist C-Type Explosive Shield Hardener"},
    {"id": 19285, "name": "Gist X-Type Explosive Shield Hardener"},
    {"id": 19276, "name": "Pith A-Type Explosive Shield Hardener"},
    {"id": 19270, "name": "Pith B-Type Explosive Shield Hardener"},
    {"id": 19260, "name": "Pith C-Type Explosive Shield Hardener"},
    {"id": 19286, "name": "Pith X-Type Explosive Shield Hardener"},
    {"id": 14759, "name": "Estamel's Modified Explosive Shield Hardener"},
    {"id": 14756, "name": "Kaikka's Modified Explosive Shield Hardener"},
    {"id": 14757, "name": "Thon's Modified Explosive Shield Hardener"},
    {"id": 14758, "name": "Vepas' Modified Explosive Shield Hardener"},

    # Kinetic Shield Hardeners
    {"id": 2299, "name": "Kinetic Shield Hardener II"},
    {"id": 17495, "name": "Caldari Navy Kinetic Shield Hardener"},
    {"id": 13997, "name": "Domination Kinetic Shield Hardener"},
    {"id": 13968, "name": "Dread Guristas Kinetic Shield Hardener"},
    {"id": 19273, "name": "Gist A-Type Kinetic Shield Hardener"},
    {"id": 19271, "name": "Gist B-Type Kinetic Shield Hardener"},
    {"id": 19257, "name": "Gist C-Type Kinetic Shield Hardener"},
    {"id": 19287, "name": "Gist X-Type Kinetic Shield Hardener"},
    {"id": 19274, "name": "Pith A-Type Kinetic Shield Hardener"},
    {"id": 19272, "name": "Pith B-Type Kinetic Shield Hardener"},
    {"id": 19258, "name": "Pith C-Type Kinetic Shield Hardener"},
    {"id": 19288, "name": "Pith X-Type Kinetic Shield Hardener"},
    {"id": 14751, "name": "Estamel's Modified Kinetic Shield Hardener"},
    {"id": 14748, "name": "Kaikka's Modified Kinetic Shield Hardener"},
    {"id": 14749, "name": "Thon's Modified Kinetic Shield Hardener"},
    {"id": 14750, "name": "Vepas' Modified Kinetic Shield Hardener"},

    # Thermal Shield Hardeners
    {"id": 2303, "name": "Thermal Shield Hardener II"},
    {"id": 20635, "name": "'Desert Heat' Thermal Shield Hardener"},
    {"id": 17497, "name": "Caldari Navy Thermal Shield Hardener"},
    {"id": 13995, "name": "Domination Thermal Shield Hardener"},
    {"id": 13966, "name": "Dread Guristas Thermal Shield Hardener"},
    {"id": 19277, "name": "Gist A-Type Thermal Shield Hardener"},
    {"id": 19267, "name": "Gist B-Type Thermal Shield Hardener"},
    {"id": 19261, "name": "Gist C-Type Thermal Shield Hardener"},
    {"id": 19283, "name": "Gist X-Type Thermal Shield Hardener"},
    {"id": 19278, "name": "Pith A-Type Thermal Shield Hardener"},
    {"id": 19268, "name": "Pith B-Type Thermal Shield Hardener"},
    {"id": 19262, "name": "Pith C-Type Thermal Shield Hardener"},
    {"id": 19284, "name": "Pith X-Type Thermal Shield Hardener"},
    {"id": 14763, "name": "Estamel's Modified Thermal Shield Hardener"},
    {"id": 14760, "name": "Kaikka's Modified Thermal Shield Hardener"},
    {"id": 14761, "name": "Thon's Modified Thermal Shield Hardener"},
    {"id": 14762, "name": "Vepas' Modified Thermal Shield Hardener"},

    # Shield Flux Coils
    {"id": 1256, "name": "Shield Flux Coil II"},
    {"id": 37825, "name": "Dread Guristas Shield Flux Coil"},

    # Shield Power Relays
    {"id": 1422, "name": "Shield Power Relay II"},
    {"id": 37820, "name": "Caldari Navy Shield Power Relay"},

    # Shield Rechargers
    {"id": 394, "name": "Shield Recharger II"},
    {"id": 37805, "name": "Republic Fleet Shield Recharger"},

    # Shield Resistance Amplifiers
    # EM Shield Amplifier
    {"id": 2553, "name": "EM Shield Amplifier II"},
    {"id": 1798, "name": "'Basic' EM Shield Amplifier"},
    {"id": 20611, "name": "'Prospector' EM Shield Amplifier"},
    {"id": 15909, "name": "Caldari Navy EM Shield Amplifier"},
    {"id": 15917, "name": "Republic Fleet EM Shield Amplifier"},
    {"id": 14041, "name": "Domination EM Shield Amplifier"},
    {"id": 14043, "name": "Dread Guristas EM Shield Amplifier"},
    {"id": 19255, "name": "Gistum A-Type EM Shield Amplifier"},
    {"id": 19247, "name": "Gistum B-Type EM Shield Amplifier"},
    {"id": 19245, "name": "Gistum C-Type EM Shield Amplifier"},
    {"id": 19231, "name": "Pithum A-Type EM Shield Amplifier"},
    {"id": 19233, "name": "Pithum B-Type EM Shield Amplifier"},
    {"id": 19215, "name": "Pithum C-Type EM Shield Amplifier"},
    {"id": 14746, "name": "Estamel's Modified EM Shield Amplifier"},
    {"id": 14630, "name": "Hakim's Modified EM Shield Amplifier"},
    {"id": 14740, "name": "Kaikka's Modified EM Shield Amplifier"},
    {"id": 14742, "name": "Thon's Modified EM Shield Amplifier"},
    {"id": 14634, "name": "Tobias' Modified EM Shield Amplifier"},
    {"id": 14744, "name": "Vepas' Modified EM Shield Amplifier"},

    # Explosive Shield Amplifier
    {"id": 2531, "name": "Explosive Shield Amplifier II"},
    {"id": 1804, "name": "'Basic' Explosive Shield Amplifier"},
    {"id": 20605, "name": "'Whiskey' Explosive Shield Amplifier"},
    {"id": 15915, "name": "Caldari Navy Explosive Shield Amplifier"},
    {"id": 15923, "name": "Republic Fleet Explosive Shield Amplifier"},
    {"id": 14029, "name": "Domination Explosive Shield Amplifier"},
    {"id": 14031, "name": "Dread Guristas Explosive Shield Amplifier"},
    {"id": 19249, "name": "Gistum A-Type Explosive Shield Amplifier"},
    {"id": 19235, "name": "Gistum B-Type Explosive Shield Amplifier"},
    {"id": 19233, "name": "Gistum C-Type Explosive Shield Amplifier"},
    {"id": 19225, "name": "Pithum A-Type Explosive Shield Amplifier"},
    {"id": 19217, "name": "Pithum B-Type Explosive Shield Amplifier"},
    {"id": 19209, "name": "Pithum C-Type Explosive Shield Amplifier"},
    {"id": 14722, "name": "Estamel's Modified Explosive Shield Amplifier"},
    {"id": 14606, "name": "Hakim's Modified Explosive Shield Amplifier"},
    {"id": 14716, "name": "Kaikka's Modified Explosive Shield Amplifier"},
    {"id": 14718, "name": "Thon's Modified Explosive Shield Amplifier"},
    {"id": 14610, "name": "Tobias' Modified Explosive Shield Amplifier"},
    {"id": 14720, "name": "Vepas' Modified Explosive Shield Amplifier"},

    # Kinetic Shield Amplifier
    {"id": 2547, "name": "Kinetic Shield Amplifier II"},
    {"id": 1802, "name": "'Basic' Kinetic Shield Amplifier"},
    {"id": 20609, "name": "'Cactus' Kinetic Shield Amplifier"},
    {"id": 15911, "name": "Caldari Navy Kinetic Shield Amplifier"},
    {"id": 15919, "name": "Republic Fleet Kinetic Shield Amplifier"},
    {"id": 14037, "name": "Domination Kinetic Shield Amplifier"},
    {"id": 14039, "name": "Dread Guristas Kinetic Shield Amplifier"},
    {"id": 19253, "name": "Gistum A-Type Kinetic Shield Amplifier"},
    {"id": 19243, "name": "Gistum B-Type Kinetic Shield Amplifier"},
    {"id": 19241, "name": "Gistum C-Type Kinetic Shield Amplifier"},
    {"id": 19229, "name": "Pithum A-Type Kinetic Shield Amplifier"},
    {"id": 19221, "name": "Pithum B-Type Kinetic Shield Amplifier"},
    {"id": 19213, "name": "Pithum C-Type Kinetic Shield Amplifier"},
    {"id": 14738, "name": "Estamel's Modified Kinetic Shield Amplifier"},
    {"id": 14622, "name": "Hakim's Modified Kinetic Shield Amplifier"},
    {"id": 14732, "name": "Kaikka's Modified Kinetic Shield Amplifier"},
    {"id": 14734, "name": "Thon's Modified Kinetic Shield Amplifier"},
    {"id": 14626, "name": "Tobias' Modified Kinetic Shield Amplifier"},
    {"id": 14736, "name": "Vepas' Modified Kinetic Shield Amplifier"},

    # Thermal Shield Amplifier
    {"id": 2539, "name": "Thermal Shield Amplifier II"},
    {"id": 1800, "name": "'Basic' Thermal Shield Amplifier"},
    {"id": 20608, "name": "'High Noon' Thermal Shield Amplifier"},
    {"id": 15913, "name": "Caldari Navy Thermal Shield Amplifier"},
    {"id": 15921, "name": "Republic Fleet Thermal Shield Amplifier"},
    {"id": 14033, "name": "Domination Thermal Shield Amplifier"},
    {"id": 14035, "name": "Dread Guristas Thermal Shield Amplifier"},
    {"id": 19251, "name": "Gistum A-Type Thermal Shield Amplifier"},
    {"id": 19239, "name": "Gistum B-Type Thermal Shield Amplifier"},
    {"id": 19237, "name": "Gistum C-Type Thermal Shield Amplifier"},
    {"id": 19227, "name": "Pithum A-Type Thermal Shield Amplifier"},
    {"id": 19219, "name": "Pithum B-Type Thermal Shield Amplifier"},
    {"id": 19211, "name": "Pithum C-Type Thermal Shield Amplifier"},
    {"id": 14730, "name": "Estamel's Modified Thermal Shield Amplifier"},
    {"id": 14614, "name": "Hakim's Modified Thermal Shield Amplifier"},
    {"id": 14724, "name": "Kaikka's Modified Thermal Shield Amplifier"},
    {"id": 14726, "name": "Thon's Modified Thermal Shield Amplifier"},
    {"id": 14618, "name": "Tobias' Modified Thermal Shield Amplifier"},
    {"id": 14728, "name": "Vepas' Modified Thermal Shield Amplifier"},

    ### Remote Shield Booster
    # Micro Shield Boosters
    {"id": 406, "name": "Micro Remote Shield Booster II"},

    # Small Shield Boosters
    {"id": 3588, "name": "Small Remote Shield Booster II"},
    {"id": 405, "name": "'Micro' Remote Shield Booster"},
    {"id": 19133, "name": "Gistii A-Type Small Remote Shield Booster"},
    {"id": 19131, "name": "Gistii B-Type Small Remote Shield Booster"},
    {"id": 19129, "name": "Gistii C-Type Small Remote Shield Booster"},
    {"id": 19139, "name": "Pithi A-Type Small Remote Shield Booster"},
    {"id": 19137, "name": "Pithi B-Type Small Remote Shield Booster"},
    {"id": 19135, "name": "Pithi C-Type Small Remote Shield Booster"},

    # Medium Shield Boosters
    {"id": 3598, "name": "Medium Remote Shield Booster II"},
    {"id": 19145, "name": "Gistii A-Type Medium Remote Shield Booster"},
    {"id": 19143, "name": "Gistii B-Type Medium Remote Shield Booster"},
    {"id": 19141, "name": "Gistii C-Type Medium Remote Shield Booster"},
    {"id": 19151, "name": "Pithi A-Type Medium Remote Shield Booster"},
    {"id": 19149, "name": "Pithi B-Type Medium Remote Shield Booster"},
    {"id": 19147, "name": "Pithi C-Type Medium Remote Shield Booster"},

    # Large Shield Boosters
    {"id": 3608, "name": "Large Remote Shield Booster II"},

    # Capital Shield Boosters
    {"id": 41483, "name": "Capital Ancillary Remote Shield Booster"},
    {"id": 41469, "name": "Capital Asymmetric Enduring Remote Shield Booster"},
    {"id": 41470, "name": "Capital Murky Compact Remote Shield Booster"},
    {"id": 3616, "name": "Capital Remote Shield Booster I"},
    {"id": 3618, "name": "Capital Remote Shield Booster II"},
    {"id": 41471, "name": "Capital S95a Scoped Remote Shield Booster"},
    {"id": 3544, "name": "CONCORD Capital Remote Shield Booster"},
    {"id": 41474, "name": "Domination Capital Remote Shield Booster"},
    {"id": 41473, "name": "Dread Guristas Capital Remote Shield Booster"},
    {"id": 41472, "name": "True Sansha Capital Remote Shield Booster"},

    # Shield Extenders
    {'name': 'Caldari Navy Small Shield Extender', 'id': 31922},
    {'name': 'Republic Fleet Small Shield Extender', 'id': 31924},
    {'name': 'Caldari Navy Medium Shield Extender', 'id': 31926},
    {'name': 'Republic Fleet Medium Shield Extender', 'id': 31928},
    {'name': 'Caldari Navy Large Shield Extender', 'id': 31930},
    {'name': 'Republic Fleet Large Shield Extender', 'id': 31932},
    {'name': 'Small Shield Extender II', 'id': 380},
    {'name': 'Medium Shield Extender II', 'id': 3831},
    {'name': 'Large Shield Extender II', 'id': 3841},
    {'name': 'Capital Shield Extender II', 'id': 40357},

    # Shield Amplifier
    {'name': 'Shield Boost Amplifier II', 'id': 24443},
    {'name': 'Pith C-Type Shield Boost Amplifier', 'id': 19289},
    {'name': 'Gist A-Type Shield Boost Amplifier', 'id': 19293},
    {'name': 'Pith X-Type Shield Boost Amplifier', 'id': 19295},
    {'name': 'Gist C-Type Shield Boost Amplifier', 'id': 19297},
    {'name': 'Gist B-Type Shield Boost Amplifier', 'id': 19299},
    {'name': 'Gist X-Type Shield Boost Amplifier', 'id': 19301},
    {'name': 'Pith B-Type Shield Boost Amplifier', 'id': 19303},
    {'name': 'Pith A-Type Shield Boost Amplifier', 'id': 19311},

    # Steel Plates
    {'name': 'Imperial Navy 100mm Steel Plates', 'id': 31896},
    {'name': 'Federation Navy 100mm Steel Plates', 'id': 31898},
    {'name': 'Imperial Navy 1600mm Steel Plates', 'id': 31900},
    {'name': 'Federation Navy 1600mm Steel Plates', 'id': 31902},
    {'name': 'Imperial Navy 200mm Steel Plates', 'id': 31904},
    {'name': 'Federation Navy 200mm Steel Plates', 'id': 31906},
    {'name': 'Imperial Navy 400mm Steel Plates', 'id': 31908},
    {'name': 'Federation Navy 400mm Steel Plates', 'id': 31910},
    {'name': 'Imperial Navy 800mm Steel Plates', 'id': 31916},
    {'name': 'Federation Navy 800mm Steel Plates', 'id': 31918},

    # Drones
    {'group_name': 'None', 'name': 'Imperial Navy Acolyte', 'id': 31864},
    {'group_name': 'None', 'name': 'Imperial Navy Infiltrator', 'id': 31866},
    {'group_name': 'None', 'name': 'Imperial Navy Curator', 'id': 31868},
    {'group_name': 'None', 'name': 'Imperial Navy Praetor', 'id': 31870},
    {'group_name': 'None', 'name': 'Caldari Navy Hornet', 'id': 31872},
    {'group_name': 'None', 'name': 'Caldari Navy Vespa', 'id': 31874},
    {'group_name': 'None', 'name': 'Caldari Navy Wasp', 'id': 31876},
    {'group_name': 'None', 'name': 'Caldari Navy Warden', 'id': 31878},
    {'group_name': 'None', 'name': 'Federation Navy Hobgoblin', 'id': 31880},
    {'group_name': 'None', 'name': 'Federation Navy Hammerhead', 'id': 31882},
    {'group_name': 'None', 'name': 'Federation Navy Ogre', 'id': 31884},
    {'group_name': 'None', 'name': 'Federation Navy Garde', 'id': 31886},
    {'group_name': 'None', 'name': 'Republic Fleet Warrior', 'id': 31888},
    {'group_name': 'None', 'name': 'Republic Fleet Valkyrie', 'id': 31890},
    {'group_name': 'None', 'name': 'Republic Fleet Berserker', 'id': 31892},
    {'group_name': 'None', 'name': 'Republic Fleet Bouncer', 'id': 31894},

    # Microwarp Drive, Afterburner (MWD, AB)
    {'name': '1MN Afterburner II', 'id': 438},
    {'name': '10MN Afterburner II', 'id': 12058},
    {'name': '100MN Afterburner II', 'id': 12068},
    {'name': '10000MN Afterburner II', 'id': 41239},
    {'name': '5MN Microwarpdrive II', 'id': 440},
    {'name': '50MN Microwarpdrive II', 'id': 12076},
    {'name': '500MN Microwarpdrive II', 'id': 12084},
    {'name': '50000MN Microwarpdrive II', 'id': 41253},

    {'name': 'Coreli C-Type 5MN Microwarpdrive', 'id': 19313},
    {'name': 'Corelum C-Type 50MN Microwarpdrive', 'id': 19315},
    {'name': 'Core C-Type 500MN Microwarpdrive', 'id': 19317},
    {'name': 'Coreli B-Type 5MN Microwarpdrive', 'id': 19319},
    {'name': 'Corelum B-Type 50MN Microwarpdrive', 'id': 19321},
    {'name': 'Core B-Type 500MN Microwarpdrive', 'id': 19323},
    {'name': 'Coreli A-Type 5MN Microwarpdrive', 'id': 19325},
    {'name': 'Corelum A-Type 50MN Microwarpdrive', 'id': 19327},
    {'name': 'Core A-Type 500MN Microwarpdrive', 'id': 19329},
    {'name': 'Core X-Type 500MN Microwarpdrive', 'id': 19335},
    {'name': 'Gistii C-Type 5MN Microwarpdrive', 'id': 19337},
    {'name': 'Gistum C-Type 50MN Microwarpdrive', 'id': 19339},
    {'name': 'Gist C-Type 500MN Microwarpdrive', 'id': 19341},
    {'name': 'Gistii B-Type 5MN Microwarpdrive', 'id': 19343},
    {'name': 'Gistum B-Type 50MN Microwarpdrive', 'id': 19345},
    {'name': 'Gist B-Type 500MN Microwarpdrive', 'id': 19347},
    {'name': 'Gistii A-Type 5MN Microwarpdrive', 'id': 19349},
    {'name': 'Gistum A-Type 50MN Microwarpdrive', 'id': 19351},
    {'name': 'Gist A-Type 500MN Microwarpdrive', 'id': 19353},
    {'name': 'Gist X-Type 500MN Microwarpdrive', 'id': 19359},
    {'name': 'Corpum B-Type EM Energized Membrane', 'id': 19361},
    {'name': 'Centum B-Type EM Energized Membrane', 'id': 19363},

    # Standard Citadels
    {'name': 'Astrahus', 'id': 35832},
    {'name': 'Fortizar', 'id': 35833},
    {'name': 'Keepstar', 'id': 35834},
    {'name': 'Tatara', 'id': 35836},
    {'name': 'Athanor', 'id': 35835},
    {'name': 'Azbel', 'id': 35826},
    {'name': 'Raitaru', 'id': 35825},
    {'name': 'Sotiyo', 'id': 35827},

    # POS
    {'name': 'Amarr Control Tower', 'id': 12235},
    {'name': 'Gallente Control Tower', 'id': 12236},
    {'name': 'Amarr Control Tower Medium', 'id': 20059},
    {'name': 'Amarr Control Tower Small', 'id': 20060},

    {'name': 'Raitaru', 'id': 35825},
    {'name': 'Raitaru', 'id': 35825},
    {'name': 'Raitaru', 'id': 35825},
    {'name': 'Raitaru', 'id': 35825},
    {'name': 'Raitaru', 'id': 35825},
    {'name': 'Raitaru', 'id': 35825},
    {'name': 'Raitaru', 'id': 35825},
    {'name': 'Raitaru', 'id': 35825},
    {'name': 'Raitaru', 'id': 35825},
    {'name': 'Raitaru', 'id': 35825},
    {'name': 'Raitaru', 'id': 35825},
    {'name': 'Raitaru', 'id': 35825},
    {'name': 'Raitaru', 'id': 35825},
    {'name': 'Raitaru', 'id': 35825},
    {'name': 'Raitaru', 'id': 35825},
    {'name': 'Raitaru', 'id': 35825},
    {'name': 'Raitaru', 'id': 35825},
    {'name': 'Raitaru', 'id': 35825},

    # Other modules
    {'name': 'Navy Micro Auxiliary Power Core', 'id': 31936},
    {'name': 'Federation Navy Omnidirectional Tracking Link', 'id': 31942},
    {'name': 'Republic Fleet Target Painter', 'id': 31944},
    {'name': 'Imperial Navy Large Remote Capacitor Transmitter', 'id': 31946},
    {'name': 'Imperial Navy Medium Remote Capacitor Transmitter', 'id': 31948},
    {'name': 'Imperial Navy Small Remote Capacitor Transmitter', 'id': 31950},
    {'name': 'Caldari Navy Power Diagnostic System', 'id': 31952},


]