items_component = [
    {"item_name": "Federation Navy Fleet Colonel Insignia I", "id": 15594},
    {"item_name": "Federation Navy Fleet Colonel Insignia II", "id": 15673},

    {"item_name": "Federation Navy Command Sergeant Major Insignia I", "id": 15646},
    {"item_name": "Federation Navy Fleet Major Insignia I", "id": 15593},

    {"item_name": "Large Shield Extender I", "id": 3839},
    {"item_name": "Medium Shield Extender I", "id": 3829},
    {"item_name": "Small Shield Extender I", "id": 377},

    {"item_name": "Cap Booster 25", "id": 263},
    {"item_name": "Cap Booster 50", "id": 264},
    {"item_name": "Cap Booster 75", "id": 3552},
    {"item_name": "Cap Booster 100", "id": 3554},
    {"item_name": "Cap Booster 150", "id": 11283},
    {"item_name": "Cap Booster 200", "id": 11285},
    {"item_name": "Cap Booster 400", "id": 11287},
    {"item_name": "Cap Booster 800", "id": 11289},
    {"item_name": "Cap Booster 3200", "id": 41489},

]


#print(items_faction_wars_state_protectorate)
items_faction_wars_state_protectorate = [
    # Shield Extenders
    {"item_name": "Caldari Navy Large Shield Extender",
     "lp_store_components": {"Federation Navy Fleet Colonel Insignia I": 2, "Federation Navy Fleet Colonel Insignia II": 4, "Large Shield Extender I": 1},
     "lp_price": 10000,
     "isk_price": 4000000,
     "quantity": 1,
     "id": 31930},

    {"item_name": "Caldari Navy Medium Shield Extender",
    "lp_store_components": {"Federation Navy Fleet Colonel Insignia I": 2, "Medium Shield Extender I": 1},
    "lp_price": 3000,
    "isk_price": 2000000,
    "quantity": 1,
    "id": 31926},

    {"item_name": "Caldari Navy Small Shield Extender",
     "lp_store_components": {"Federation Navy Command Sergeant Major Insignia I": 2, "Small Shield Extender I": 1, "Federation Navy Fleet Major Insignia I": 4},
     "lp_price": 1000,
     "isk_price": 500000,
     "quantity": 1,
     "id": 31922,},

    # DataCore
    {"item_name": "Datacore - Quantum Physics",
     "lp_store_components": {},
     "lp_price": 250,
     "isk_price": 250000,
     "quantity": 5,
     "id": 20414,},
    {"item_name": "Datacore - Rocket Science",
     "lp_store_components": {},
     "lp_price": 250,
     "isk_price": 250000,
     "quantity": 5,
     "id": 20420,},
    {"item_name": "Datacore - Graviton Physics",
     "lp_store_components": {},
     "lp_price": 250,
     "isk_price": 250000,
     "quantity": 5,
     "id": 20419,},
    {"item_name": "Datacore - Caldari Starship Engineering",
     "lp_store_components": {},
     "lp_price": 250,
     "isk_price": 250000,
     "quantity": 5,
     "id": 25887,},
    {"item_name": "Datacore - Mechanical Engineering",
     "lp_store_components": {},
     "lp_price": 250,
     "isk_price": 250000,
     "quantity": 5,
     "id": 20424,},

    # Cap Booster
    {"item_name": "Navy Cap Booster 25",
     "lp_store_components": {"Cap Booster 25": 20},
     "lp_price": 60,
     "isk_price": 60000,
     "quantity": 20,
     "id": 33330, },
    {"item_name": "Navy Cap Booster 50",
     "lp_store_components": {"Cap Booster 50": 20},
     "lp_price": 125,
     "isk_price": 125000,
     "quantity": 20,
     "id": 33332, },
    {"item_name": "Navy Cap Booster 75",
     "lp_store_components": {"Cap Booster 75": 20},
     "lp_price": 185,
     "isk_price": 185000,
     "quantity": 20,
     "id": 33334, },
    {"item_name": "Navy Cap Booster 150",
     "lp_store_components": {"Cap Booster 150": 20},
     "lp_price": 375,
     "isk_price": 375000,
     "quantity": 20,
     "id": 31990, },
    {"item_name": "Navy Cap Booster 200",
     "lp_store_components": {"Cap Booster 200": 20},
     "lp_price": 500,
     "isk_price": 500000,
     "quantity": 20,
     "id": 31998, },
    {"item_name": "Navy Cap Booster 400",
     "lp_store_components": {"Cap Booster 400": 20},
     "lp_price": 1000,
     "isk_price": 1000000,
     "quantity": 20,
     "id": 32006, },
    {"item_name": "Navy Cap Booster 800",
     "lp_store_components": {"Cap Booster 800": 20},
     "lp_price": 2000,
     "isk_price": 2000000,
     "quantity": 20,
     "id": 32014, },
    {"item_name": "Navy Cap Booster 3200",
     "lp_store_components": {"Cap Booster 3200": 20},
     "lp_price": 8000,
     "isk_price": 8000000,
     "quantity": 20,
     "id": 41490, },

]

#for item in items_faction_wars_state_protectorate:
#    for component, quantity in item["lp_store_components"].items():
#        print(f"Component: {component}, Quantity: {quantity}")
